// GENERATED by scripts/pull-notion-lessons.mjs — do not edit by hand.
// Source: the 52-Week Curriculum Notion boards (Week 1, each track).
//
// Public-safety filter: this file carries ONLY what a visitor may see —
// the idea, the questions and the practice. Slide notes, facilitator
// notes, safeguarding material, evidence/source trails and join codes are
// never parsed into here. See src/lib/curriculumPublic.ts for the rule.

export interface LessonOneTrackPreview {
  title: string;
  blockTheme: string;
  weeklyTheme: string;
  sharedCoreConcept: string;
  trackTranslation: string;
  territory: string;
  openingQuestion: string;
  ancientWisdom: string;
  todaysWorld: string;
  coreConcept: string;
  videoDescription: string;
  reflectiveQuestions: string;
  intentionPrompt: string;
  weeklyPractice: string;
  affirmation: string;
}

export const LESSON_ONE_PREVIEW: Record<
  "adult" | "teen" | "child",
  LessonOneTrackPreview
> = {
  adult: {
    title: "What Are You Actually Receiving?",
    blockTheme: "See Clearly",
    weeklyTheme: "The Signal and the Noise",
    sharedCoreConcept: "We are always receiving signals from our body, thoughts, other people and the world around us. The skill is to notice what is arriving, work out where it came from, and choose what deserves our attention.",
    trackTranslation: "Notice which inputs are shaping your attention and thinking, then decide what to keep, question or set aside.",
    territory: "Noticing what's going on inside you when everything is noisy",
    openingQuestion: "What is one thing that has taken up more of your attention this week than you intended?",
    ancientWisdom: "For centuries, navigators had to travel without GPS, maps updating in real time, or a voice telling them exactly where to turn. They relied on reference points — stars, landmarks, compass bearings and repeated checks of their position — because when you are moving for a long time, drift can be hard to notice from inside the boat.",
    todaysWorld: "In the past, navigation meant checking an external reference point because drift was difficult to feel while you were moving. Today, much of the drift happens in our attention.  All day, things are pulling at our attention: notifications, conversations, expectations whatever the algorithm decides to put in front of us next. We can slowly drift toward whatever is loudest or most repeated without ever consciously deciding that it deserves our attention. Another person’s mood or opinion can quickly become the loudest thing in the room.",
    coreConcept: "The lesson from the….. navigator is not that there is some perfect inner voice we need to uncover. A feeling can be strong and still be wrong. A thought can feel familiar and still have come from somewhere else. The useful practice is simply to stop occasionally and check our direction.",
    videoDescription: "In her talk, Dr. Tasha Eurich explains that asking \"why\" often keeps us trapped in our own heads, leading to rumination and \"alternative facts\" (11:17). Shifting to \"what\" questions helps us move forward and focus on productive actions (15:49).\nExamples of the Shift\nWork Stress:\nWhy: \"Why am I so bad at these presentations?\" (7:50)\nWhat: \"What can I do to be better prepared for my next presentation?\" (12:40)\nRelationship Conflict:\nWhy: \"Why is my partner so annoying about the dishwasher?\" (11:05)\nWhat: \"What is a way we can compromise on the kitchen chores to reduce stress?\" (15:49)\nPersonal Setbacks:\nWhy: \"Why does this always happen to me?\"\nWhat: \"What are the common factors in these situations that I can influence?\" (13:36)",
    reflectiveQuestions: "To apply this to your own life, try this exercise:\nThink of a recent moment where you found yourself spiraling or feeling stuck after asking yourself \"why.\"\n1. Write down the specific \"why\" question you asked yourself in that moment.\n2. Now, rewrite it as a \"what\" question that focuses on a constructive next step.\n3. Looking back at that situation, what is one actionable \"what\" question you could have asked yourself instead to shift from feeling stuck to moving forward?",
    intentionPrompt: "Before You Leave - Write down one specific thing you will do this week.\nIt goes in your workbook — and it comes back with you next Sunday.\nAdd it in the app · code MEYBGT\nPrivate to you — it is not shown on screen\nWrite one small if-then plan for the next seven days: When I notice [a specific cue] capturing my attention, I will [take one small action]. Keep the action small enough to do on a bad day.",
    weeklyPractice: "- SUN (TODAY) — Catch one input. Once today, notice something that arrived before you chose it — a notification, someone's mood, a comment that stuck. Write down where it came from, or write \"not sure\".\n- WED — Ask what, not why. Next time you react to something, ask yourself \"what happened just before that?\" Write one observable answer before you add an explanation.\n- FRI — Find the quiet channel. Before you come back, take five minutes with no input at all — no phone, no music, no list. Notice what is still there underneath and bring one sentence about it, if you want to.",
    affirmation: "I can notice what is reaching me and choose what deserves my attention.",
  },
  teen: {
    title: "Who's Actually Talking?",
    blockTheme: "See Clearly",
    weeklyTheme: "The Signal and the Noise",
    sharedCoreConcept: "We are always receiving signals from our body, thoughts, other people and the world around us. The skill is to notice what is arriving, work out where it came from, and choose what deserves our attention.",
    trackTranslation: "Notice which opinions, reactions and expectations you picked up from people, feeds or past experiences, then decide what you actually want to do with them.",
    territory: "Noticing what's going on inside you when everything is noisy",
    openingQuestion: "What is one thing taking up a lot of your attention lately — a trend, group chat, game, person, expectation, school, or something else?",
    ancientWisdom: "For centuries, navigators travelled without GPS, live maps or a voice telling them exactly where to turn.\nThey repeatedly checked stars, landmarks and bearings because when you have been travelling in one direction for long enough, drift can be difficult to notice from inside the boat.",
    todaysWorld: "Today, drift can happen in our opinions and attention.\nA fashion trend, joke, slang word, group opinion, viral video or expectation can suddenly seem to be everywhere.\nWhen we see or hear something repeatedly — especially from people we care about — it can start to feel normal before we have consciously decided what we think about it.\nFamiliar is not the same as true.\nAnd being influenced by other people does not mean you are fake.\nThe useful question is:\nWhere did this come from — and do I still want to keep heading in that direction?",
    coreConcept: "Today the teen room looks at how influence becomes familiar.\nThe goal is not to reject what came from other people.\nIt is to notice where an opinion, label or expectation may have come from, then decide whether it still fits what you know and value now.",
    videoDescription: "This segment explores how people naturally use those around them to work out what is normal, expected or accepted.\nIt introduces Solomon Asch’s conformity experiments, where participants sometimes gave an obviously incorrect answer after hearing the rest of a group give that answer first.\nIt also introduces normative social influence — going along with a group because belonging, acceptance or avoiding social disapproval matters to us.\nThe point is not that following other people is bad.\nWe all use other people as information.\nThe skill is noticing when the group is influencing your choice strongly enough that you want to pause and check your own view.",
    reflectiveQuestions: "1. Why do you think it became harder to give a different answer once everyone else in the group had already answered?\n2. Where does something similar happen in everyday teenage life — without anyone deliberately trying to pressure someone?\n3. Can something come from a group and still be something you genuinely agree with?\n4. What could give you one extra moment to choose before automatically going along with everyone else?",
    intentionPrompt: "Before You Leave — Write down one specific thing you will practise this week.\nIt goes in your workbook — and it comes back with you next Sunday.\nAdd it in the app · code MEYBGT\nPrivate to you — it is not shown on screen.\nWrite one small if-then plan:\nWhen I notice [a specific pressure, trend, opinion, label or cue], I will [take one small action that gives me a moment to choose].\nKeep the action small enough to use in real life.\nExamples:\nWhen I notice myself agreeing immediately because everyone else agrees, I will pause for three seconds before answering.\nWhen I notice myself thinking “everyone thinks this”, I will ask myself who “everyone” actually is.\nWhen I notice myself changing an opinion because of a group chat, I will name what I thought before I read everyone else's responses.",
    weeklyPractice: "- SUN (TODAY) — Set your intention. Once today, notice one moment where another person, group, trend or feed influences what you think, say or do. You do not need to change anything yet. Just notice it.\n- WED — Return to your intention. Ask: Did I notice it? Could I name what was influencing me? Did I do anything differently? Then ask: What happened right before that?\n- FRI — Return to your intention again. Mark where you got to: didn't notice / noticed but couldn't name / noticed and named / noticed, named and acted. Write one sentence about what helped or what got in the way.",
    affirmation: "I can notice what is influencing me and choose what still fits me.",
  },
  child: {
    title: "Finding Your Station",
    blockTheme: "See Clearly",
    weeklyTheme: "The Signal and the Noise",
    sharedCoreConcept: "We are always receiving signals from our body, thoughts, other people and the world around us. The skill is to notice what is arriving, work out where it came from, and choose what deserves our attention.",
    trackTranslation: "Notice body and feeling signals using movement, pictures and simple words, then choose whether to keep noticing, take a break or ask a trusted grown-up for help.",
    territory: "Noticing one small signal when lots of things are happening",
    openingQuestion: "",
    ancientWisdom: "",
    todaysWorld: "",
    coreConcept: "Today the child room practises noticing one concrete signal at a time.\nWe do not have to decide exactly what a tummy, face, heart or pair of wiggly legs means.\nWe notice it, name what we can, and choose whether to keep noticing, take a break or ask a trusted grown-up for help.",
    videoDescription: "",
    reflectiveQuestions: "",
    intentionPrompt: "One thing I want to work on this week is...",
    weeklyPractice: "- SUN (TODAY) — Be a Body Detective. Notice one body signal today — hungry, wiggly, warm, tired, tight, loose or something else. You can name it, draw it or show a trusted grown-up.\n- WED — Notice your body again. If it wants your attention, try one small thing: a stretch, a drink of water, some movement, a quiet space, a pause or asking a trusted grown-up for help. See if anything changes. It is okay if nothing changes.\n- FRI — Think back over your week. What was one body signal you noticed? You can draw it or tell a trusted grown-up. You do not have to know exactly what it meant.",
    affirmation: "I can notice my body's signals without having to know exactly what they mean.",
  },
};
