project_id = "gjkhkaywozuobhbcdysi"

[functions.buy-worksheet]
verify_jwt = false

[functions.generate-session-video]
verify_jwt = true

[functions.shotstack-webhook]
verify_jwt = false

[functions.bulk-generate-videos]
verify_jwt = true

[functions.send-practice-reminder]
verify_jwt = false

[functions.select-weekly-callbacks]
verify_jwt = false

[functions.nfc-checkin]
verify_jwt = false
