// Lesson 1, opened up — what each room actually covers in the first session.
//
// Content comes from src/lib/lessonOnePreview.ts, generated by
// scripts/pull-notion-lessons.mjs from the founder's Notion lesson boards and
// filtered to the public-safe subset (the idea, the questions, the practice —
// never slide notes or facilitator material).

import { LESSON_ONE_PREVIEW } from "@/lib/lessonOnePreview";
import type { Track } from "@/hooks/useCurriculumWeeks";

const Label = ({ children }: { children: string }) => (
  <p className="font-body text-[9px] font-bold uppercase tracking-[0.24em] text-primary">
    {children}
  </p>
);

const Quote = ({ children }: { children: string }) => (
  <p
    className="text-lg italic leading-[1.55] text-[#304c63] sm:text-xl"
    style={{ fontFamily: "var(--font-serif)" }}
  >
    {children}
  </p>
);

/** Paragraphs with their line breaks kept — lesson copy is written deliberately. */
const Copy = ({ children }: { children: string }) => (
  <div className="space-y-3">
    {children.split(/\n+/).filter(Boolean).map((line, i) => (
      <p key={i} className="font-body text-sm leading-6 text-[#4a5a6a]">
        {line}
      </p>
    ))}
  </div>
);

const Block = ({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) => (
  <div className="border-t border-[#e6ded2] pt-5">
    <Label>{label}</Label>
    <div className="mt-3">{children}</div>
  </div>
);

const LessonOnePreview = ({ track }: { track: Track }) => {
  const lesson = LESSON_ONE_PREVIEW[track];

  return (
    <div className="rounded-2xl border border-[#ddd4c7] bg-[#fdfbf7] p-6 sm:p-9">
      {/* The lesson's own title block */}
      <p className="font-body text-[10px] font-bold uppercase tracking-[0.24em] text-primary">
        Week 1 · {lesson.blockTheme}
      </p>

      <h4 className="mt-3 font-display text-4xl leading-[0.95] tracking-tight text-[#102438] sm:text-5xl">
        {lesson.title.toUpperCase()}
      </h4>

      {lesson.weeklyTheme ? (
        <p className="mt-3 font-body text-xs font-semibold uppercase tracking-[0.16em] text-[#71808e]">
          Weekly theme · {lesson.weeklyTheme}
        </p>
      ) : null}

      {lesson.territory ? (
        <p
          className="mt-5 max-w-[62ch] text-lg italic leading-[1.55] text-[#304c63]"
          style={{ fontFamily: "var(--font-serif)" }}
        >
          {lesson.territory}
        </p>
      ) : null}

      <div className="mt-8 space-y-6">
        {lesson.sharedCoreConcept ? (
          <Block label="The shared idea — every room starts here">
            <Quote>{lesson.sharedCoreConcept}</Quote>
          </Block>
        ) : null}

        {lesson.trackTranslation ? (
          <Block label="How this room takes it">
            <Copy>{lesson.trackTranslation}</Copy>
          </Block>
        ) : null}

        {lesson.openingQuestion ? (
          <Block label="The opening question">
            <Quote>{lesson.openingQuestion}</Quote>
          </Block>
        ) : null}

        {lesson.ancientWisdom ? (
          <Block label="Ancient wisdom">
            <Copy>{lesson.ancientWisdom}</Copy>
          </Block>
        ) : null}

        {lesson.todaysWorld ? (
          <Block label="In today's world">
            <Copy>{lesson.todaysWorld}</Copy>
          </Block>
        ) : null}

        {lesson.coreConcept ? (
          <Block label="The core concept">
            <Copy>{lesson.coreConcept}</Copy>
          </Block>
        ) : null}

        {lesson.videoDescription ? (
          <Block label="This week's listen">
            <Copy>{lesson.videoDescription}</Copy>
          </Block>
        ) : null}

        {lesson.reflectiveQuestions ? (
          <Block label="Reflective questions">
            <Copy>{lesson.reflectiveQuestions}</Copy>
          </Block>
        ) : null}

        {lesson.intentionPrompt ? (
          <Block label="The intention — a 90-second private write">
            <Quote>{lesson.intentionPrompt}</Quote>
          </Block>
        ) : null}

        {lesson.weeklyPractice ? (
          <Block label="The weekly practice">
            <Copy>{lesson.weeklyPractice}</Copy>
          </Block>
        ) : null}

        {lesson.affirmation ? (
          <Block label="The closing affirmation">
            <Quote>{lesson.affirmation}</Quote>
          </Block>
        ) : null}
      </div>
    </div>
  );
};

export default LessonOnePreview;
