-- Teen + child variants of the modern 'signal metaphor'. Same idea as the adult
-- metaphor for each week, retuned for the age: teen = school / phones / group
-- chats / gaming; child (4-11) = simple, playful, feeling-first (echoing the
-- colouring-page imagery). Stored on curriculum_weeks and mirrored per audience
-- onto mindcast_live_sessions so each track's facilitator slide shows its version.

ALTER TABLE public.curriculum_weeks
  ADD COLUMN IF NOT EXISTS teen_signal_metaphor text DEFAULT '',
  ADD COLUMN IF NOT EXISTS kids_signal_metaphor text DEFAULT '';

UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Your brain''s like your phone with every app open and buzzing — the signal is the one thing that actually matters. Today: flick on Do Not Disturb for a minute and notice the quiet.', kids_signal_metaphor = 'Your mind can get loud like a room full of shouting toys. Take a big breath and find the quiet voice inside — that''s the real you.', updated_at = now() WHERE week_number = 1;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'The things you believe about yourself are like an old status you never updated — and half of them aren''t even true. Today: catch one ''I''m not…'' and ask who typed that.', kids_signal_metaphor = 'Sometimes we carry heavy ''story stones'' like ''I can''t''. You can set one down and pick up a lighter one: ''I can try''.', updated_at = now() WHERE week_number = 2;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Between someone''s annoying comment and your comeback there''s a tiny gap — that gap is your power button. Today: press pause once before you react.', kids_signal_metaphor = 'When a big feeling comes, press your own PAUSE button and count 1-2-3 before you do anything.', updated_at = now() WHERE week_number = 3;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Your body sends notifications before your brain does — butterflies, tight chest, hot face. Today: read one before a stressful moment instead of ignoring it.', kids_signal_metaphor = 'Your body talks to you! Butterflies in your tummy or a hot face — where do YOU feel your feelings?', updated_at = now() WHERE week_number = 4;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Your front camera shows every flaw; a real mate sees you laughing. Today: look at yourself the way your best friend does.', kids_signal_metaphor = 'Look in the mirror and say something kind to yourself, just like a good friend would.', updated_at = now() WHERE week_number = 5;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Comparing your life to everyone''s feed is comparing your bloopers to their highlight reel. Today: mute one account that quietly makes you feel small.', kids_signal_metaphor = 'You''re your very own puzzle — nobody else has your pieces. You don''t need to be like anyone else.', updated_at = now() WHERE week_number = 6;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'That mean voice in your head is like a hater in the comments — you can mute it and keep a coach. Today: talk to yourself the way you''d talk to your best mate.', kids_signal_metaphor = 'If a grumpy gremlin says mean things inside, don''t listen — listen to the kind coach who says ''you can do it''.', updated_at = now() WHERE week_number = 7;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Being ''angry'' is usually just the top layer — scared, hurt or tired is underneath. Today: dig one feeling one level deeper.', kids_signal_metaphor = 'Angry is like the tip of an iceberg — underneath might be sad or scared. What''s under yours?', updated_at = now() WHERE week_number = 8;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Old hurts are like a heavy bag you forgot you''re even carrying. Today: tell one safe person one thing you''ve been carrying.', kids_signal_metaphor = 'Everyone has hurts, like a little stone in their pocket. You don''t have to carry it alone — safe people help.', updated_at = now() WHERE week_number = 9;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Your finsta is closer to the real you than your main account. Today: show the real you to one person you trust.', kids_signal_metaphor = 'Sometimes we wear a pretend face. The people who love you want to see the real, wonderful you.', updated_at = now() WHERE week_number = 10;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'The person who snapped at you might be having the worst day of their life — you just can''t see it. Today: give one person the benefit of the doubt.', kids_signal_metaphor = 'Everyone has a story you can''t see. Be kind — you never know what someone might be feeling.', updated_at = now() WHERE week_number = 11;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'A habit is autoplay — one trigger and the next thing just happens. Today: swap one autoplay action on purpose.', kids_signal_metaphor = 'Habits are like a path you walk again and again. You can choose to make a new, better path.', updated_at = now() WHERE week_number = 12;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'You''ve unlocked a toolkit this term — a pause button, a mute button, a feelings map. Today: pick the one you''ll actually keep.', kids_signal_metaphor = 'You''ve learned lots of tools — a pause button, a feelings map, a kind coach. Which one will you keep in your pocket?', updated_at = now() WHERE week_number = 13;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'You keep waiting to get ''picked'' — but you''re allowed to pick yourself. Today: give yourself the green light on one thing.', kids_signal_metaphor = 'You don''t have to wait for a turn to try something good. Give yourself a big green GO!', updated_at = now() WHERE week_number = 14;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'You''ve been playing a character other people wrote for you. Today: do one small thing that''s actually YOU.', kids_signal_metaphor = 'You don''t have to be who others say. You get to make your own special mark, like the first dot on a page.', updated_at = now() WHERE week_number = 15;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Holding a grudge is holding a hot chip — you''re the one it burns. Today: let one go.', kids_signal_metaphor = 'Holding a mad feeling is like holding a hot stone. Open your hand and let it go — you''ll feel better.', updated_at = now() WHERE week_number = 16;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'You already paid for that mistake — stop charging yourself for it on repeat. Today: mark it ''lesson learned'' and move on.', kids_signal_metaphor = 'Everyone makes mistakes. Say sorry, make it right, and be kind to yourself — you''re still learning.', updated_at = now() WHERE week_number = 17;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Swap the hater in your head for a coach — same honesty, kinder tone. Today: rewrite one harsh thought the way a coach would.', kids_signal_metaphor = 'Turn the grumpy gremlin into a kind coach who says: ''You can do it, keep trying.''', updated_at = now() WHERE week_number = 18;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Saying yes to everything drains your battery to 1% by lunch. Today: say one honest ''no''.', kids_signal_metaphor = 'It''s okay to say ''no'' sometimes. Your ''yes'' means more when it comes from your heart.', updated_at = now() WHERE week_number = 19;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Kindness isn''t snacks that run out — it''s a phone charger that charges someone else and stays full. Today: give some away.', kids_signal_metaphor = 'Some things grow when you share them — like kindness and love! The more you give, the more there is.', updated_at = now() WHERE week_number = 20;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'You picked up ''settings'' from the people who raised you — some are great, some need updating. Today: notice one you''d change.', kids_signal_metaphor = 'The people who love us teach us things. Keep the good lessons and gently let go of the ones that don''t help.', updated_at = now() WHERE week_number = 21;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'The tough act that once protected you now keeps good people out. Today: drop it a little with one safe person.', kids_signal_metaphor = 'Sometimes we build a wall to feel safe. But a wall can have a little door for the people we trust.', updated_at = now() WHERE week_number = 22;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Winter looks empty but it''s just clearing space for spring. Today: name what an ending has made room for.', kids_signal_metaphor = 'Even when the leaves fall, the tree isn''t gone — it''s resting and getting ready to grow again.', updated_at = now() WHERE week_number = 23;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Most ''panic'' is burnt toast, not a real fire — the alarm just can''t tell the difference. Today: label one fear ''burnt toast'' and breathe.', kids_signal_metaphor = 'Sometimes the worry alarm goes off for burnt toast, not a real fire. Take a breath — you are safe.', updated_at = now() WHERE week_number = 24;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'An old ''I always mess this up'' is a saved route that doesn''t go where you live now. Today: set a new destination.', kids_signal_metaphor = 'An old story like ''I always get it wrong'' can be rewritten. You get to add new, truer pages.', updated_at = now() WHERE week_number = 25;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'You''ve deleted some heavy apps this term — grudges, armour, pressure. Today: notice how much lighter you run.', kids_signal_metaphor = 'You''ve put down some heavy stones and picked up some light feathers. Doesn''t that feel lighter?', updated_at = now() WHERE week_number = 26;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'You don''t have to keep the labels people stuck on you — pack your own bag. Today: pick three qualities you''re built from.', kids_signal_metaphor = 'You get to choose what you''re made of — kind, brave, curious. Which bricks will you build with?', updated_at = now() WHERE week_number = 27;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Your values are your GPS ''home'' setting — lock it in and choices get easier. Today: name your top one.', kids_signal_metaphor = 'A compass points the way. Your kindness and honesty are like your own compass inside.', updated_at = now() WHERE week_number = 28;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'You don''t level up in one epic session — you grind small and daily. Today: pick one 1% habit to repeat.', kids_signal_metaphor = 'A tiny seed watered every day grows big. Small good habits grow YOU big too.', updated_at = now() WHERE week_number = 29;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Your body''s the console everything runs on — sleep, food, moving and chill are the charge cables. Today: plug in the one that''s flat.', kids_signal_metaphor = 'Your body is like a superhero suit — sleep, food, moving and calm keep it charged up!', updated_at = now() WHERE week_number = 30;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'You become the average of your closest few — choose your circle on purpose. Today: invest in one good friend.', kids_signal_metaphor = 'Good friends are like a garden growing side by side, helping each other stand tall.', updated_at = now() WHERE week_number = 31;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Talk to yourself like a mate, not a hater in the comments. Today: keep one kind phrase ready for a hard moment.', kids_signal_metaphor = 'Talk to yourself kindly, like talking to a friend: ''I can be scared AND brave.''', updated_at = now() WHERE week_number = 32;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Routine isn''t boring — it''s the frame that actually gives you more free time. Today: add one anchor to your day.', kids_signal_metaphor = 'A day with a gentle rhythm — wake, play, rest — helps you feel calm and happy.', updated_at = now() WHERE week_number = 33;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'You charge your phone before it dies, not after — do the same for you. Today: plan real rest before you crash.', kids_signal_metaphor = 'Even superheroes need to rest and recharge. Resting isn''t being lazy — it''s getting stronger.', updated_at = now() WHERE week_number = 34;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Making stuff for fun (not for likes) actually feeds you. Today: make one thing nobody will grade.', kids_signal_metaphor = 'Make something just because it''s fun! It doesn''t have to be perfect — the making is the joy.', updated_at = now() WHERE week_number = 35;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Purpose is where what you''re good at meets what the world needs. Today: spot one small overlap.', kids_signal_metaphor = 'You have a special gift the world needs — like the puzzle piece that completes the picture.', updated_at = now() WHERE week_number = 36;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Your money habits are hand-me-downs — needs, wants and sharing can be sorted on purpose. Today: sort one thing.', kids_signal_metaphor = 'Some things we need, some we want, and some we can share. Sharing feels really good!', updated_at = now() WHERE week_number = 37;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'A crew is a beehive — it works because everyone brings something back. Today: bring one thing to your group.', kids_signal_metaphor = 'A community is like a beehive — everyone brings something to help. What will you bring?', updated_at = now() WHERE week_number = 38;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Your building site is now a place you can live in — values, habits, people. Today: name who you''ve become.', kids_signal_metaphor = 'You''ve built something wonderful inside — now it''s time to live it. Look how much you''ve grown!', updated_at = now() WHERE week_number = 39;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'You share the wifi password once you''re connected — share what you''ve learned too. Today: help one person with it.', kids_signal_metaphor = 'When you learn something good, share it! Helping others makes the good even bigger.', updated_at = now() WHERE week_number = 40;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'You really learn something when you can explain it simply. Today: teach one thing in a single sentence.', kids_signal_metaphor = 'Teaching a friend what you know helps you both. What could you teach in one sentence?', updated_at = now() WHERE week_number = 41;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Camera-on is scary for two seconds and connecting for the rest. Today: show up honestly somewhere you usually hide.', kids_signal_metaphor = 'The real you is wonderful. It''s brave and good to let people see the true you.', updated_at = now() WHERE week_number = 42;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Your values are only real when they actually cost you something. Today: hold one even when it''s hard.', kids_signal_metaphor = 'Doing the right thing can be hard, like holding a compass in a storm. Hold on to what you know is kind.', updated_at = now() WHERE week_number = 43;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = '''You always…'' starts a fight; ''I feel… I need…'' starts a conversation. Today: try the second one.', kids_signal_metaphor = 'When you''re upset with a friend, say ''I feel...'' and ''I need...'' — it helps you both.', updated_at = now() WHERE week_number = 44;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Some gifts cost nothing and still glow — time, help, a good word. Today: give one.', kids_signal_metaphor = 'You can give gifts that aren''t money — a smile, a helping hand, a kind word. They''re the best kind!', updated_at = now() WHERE week_number = 45;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = '''One more thing'' never becomes enough — it''s a treadmill. Today: name three things you already have that are enough.', kids_signal_metaphor = 'You already have so many good things! Let''s notice them and feel grateful.', updated_at = now() WHERE week_number = 46;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'A seed looks like nothing while it grows roots underground — don''t quit early. Today: recommit to one slow thing.', kids_signal_metaphor = 'A seed grows underground before you can see it. Keep going — you''re growing even when it doesn''t show!', updated_at = now() WHERE week_number = 47;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Every interaction leaves a tip — a bit brighter or a bit dimmer. Today: leave one person brighter.', kids_signal_metaphor = 'You can be a sunshine person, making others a little brighter wherever you go!', updated_at = now() WHERE week_number = 48;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Drop a stone in a pond and the ripples reach places you''ll never see. Today: name one mark you want to leave.', kids_signal_metaphor = 'Your kindness makes ripples, like a stone in a pond, reaching further than you can see.', updated_at = now() WHERE week_number = 49;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'Gratitude is a camera — the more you point it, the more good it finds. Today: name three specific good things.', kids_signal_metaphor = 'Gratitude is like a camera for good things. Snap three you''re thankful for today!', updated_at = now() WHERE week_number = 50;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'There''s no ''you win'' screen for growing up — the game itself is the point. Today: pick one practice to keep for life.', kids_signal_metaphor = 'You never finish growing — and that''s the fun part! Keep going, the adventure continues.', updated_at = now() WHERE week_number = 51;
UPDATE public.curriculum_weeks SET teen_signal_metaphor = 'You''re not closing the book, you''re on a fresh page with a full backpack. Today: write the first line of your next chapter.', kids_signal_metaphor = 'Look how far you''ve come this year! The story isn''t finished — it''s just beginning.', updated_at = now() WHERE week_number = 52;

-- Mirror the right variant onto each audience's live-session row.
UPDATE public.mindcast_live_sessions ms
SET signal_metaphor = CASE ms.audience
      WHEN 'Teen'  THEN NULLIF(cw.teen_signal_metaphor, '')
      WHEN 'Child' THEN NULLIF(cw.kids_signal_metaphor, '')
      ELSE NULLIF(cw.signal_metaphor, '')
    END
FROM public.curriculum_weeks cw
WHERE ms.week_number = cw.week_number
  AND CASE ms.audience
        WHEN 'Teen'  THEN NULLIF(cw.teen_signal_metaphor, '')
        WHEN 'Child' THEN NULLIF(cw.kids_signal_metaphor, '')
        ELSE NULLIF(cw.signal_metaphor, '')
      END IS NOT NULL;

