-- Admin membership reporting foundation.
--
-- This migration deliberately does not create new membership, attendance,
-- household, session or journal systems. It adds the minimum immutable metadata
-- required to report those existing systems accurately over time:
--   * membership status transitions (profiles remains the current-state mirror)
--   * journal field empty/non-empty transitions (never journal content)
--   * database-driven programme locations
--   * subscription MRR snapshots captured from future Stripe webhook events
--
-- Historical warning: the baseline rows written below describe state at the
-- moment this migration runs. They are not backdated and must not be presented
-- as reconstructed history.

-- ---------------------------------------------------------------------------
-- 1. Dynamic programme locations and future facilitator attribution
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.programme_locations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  timezone text NOT NULL DEFAULT 'Pacific/Auckland',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.programme_locations ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.programme_locations TO authenticated;
GRANT ALL ON public.programme_locations TO service_role;

DROP POLICY IF EXISTS "programme_locations_authenticated_read" ON public.programme_locations;
CREATE POLICY "programme_locations_authenticated_read" ON public.programme_locations
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "programme_locations_admin_manage" ON public.programme_locations;
CREATE POLICY "programme_locations_admin_manage" ON public.programme_locations
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::app_role))
  WITH CHECK (public.has_role(auth.uid(), 'admin'::app_role));

INSERT INTO public.programme_locations (code, name)
VALUES ('taupo', 'Taupō')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS home_location_id uuid
    REFERENCES public.programme_locations(id) ON DELETE SET NULL;

ALTER TABLE public.scheduled_sessions
  ADD COLUMN IF NOT EXISTS location_id uuid
    REFERENCES public.programme_locations(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS facilitator_profile_id uuid
    REFERENCES public.profiles(id) ON DELETE SET NULL;

ALTER TABLE public.scheduled_sessions
  DROP CONSTRAINT IF EXISTS scheduled_sessions_session_date_track_key;

CREATE UNIQUE INDEX IF NOT EXISTS scheduled_sessions_date_track_location_key
  ON public.scheduled_sessions (session_date, track, location_id) NULLS NOT DISTINCT;

-- Mindcast currently operates in Taupō. The value is a seeded database row,
-- not a UI constant; future locations automatically flow into report filters.
UPDATE public.profiles
SET home_location_id = (SELECT id FROM public.programme_locations WHERE code = 'taupo')
WHERE home_location_id IS NULL;

UPDATE public.scheduled_sessions
SET location_id = (SELECT id FROM public.programme_locations WHERE code = 'taupo')
WHERE location_id IS NULL;

CREATE OR REPLACE FUNCTION public.assign_default_programme_location()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.location_id IS NULL THEN
    SELECT id INTO NEW.location_id
    FROM public.programme_locations
    WHERE is_active
    ORDER BY CASE WHEN code = 'taupo' THEN 0 ELSE 1 END, created_at
    LIMIT 1;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS assign_default_programme_location ON public.scheduled_sessions;
CREATE TRIGGER assign_default_programme_location
  BEFORE INSERT OR UPDATE ON public.scheduled_sessions
  FOR EACH ROW EXECUTE FUNCTION public.assign_default_programme_location();

CREATE INDEX IF NOT EXISTS profiles_home_location_idx
  ON public.profiles (home_location_id);
CREATE INDEX IF NOT EXISTS scheduled_sessions_reporting_idx
  ON public.scheduled_sessions (session_date, track, location_id, status);
CREATE INDEX IF NOT EXISTS scheduled_sessions_facilitator_idx
  ON public.scheduled_sessions (facilitator_profile_id);

-- ---------------------------------------------------------------------------
-- 2. Immutable membership status history
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.membership_status_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  status text NOT NULL
    CHECK (status IN ('active','trialing','past_due','lapsed','paused','none')),
  membership_tier text NOT NULL DEFAULT 'none'
    CHECK (membership_tier IN ('none','adult','teen','child')),
  effective_at timestamptz NOT NULL DEFAULT now(),
  source text NOT NULL DEFAULT 'profile_update',
  is_baseline boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.membership_status_events ENABLE ROW LEVEL SECURITY;
-- No client table policy by design. Admin reporting is exposed only through
-- aggregate/security-definer RPCs below; service role and triggers can write.

CREATE INDEX IF NOT EXISTS membership_status_events_profile_time_idx
  ON public.membership_status_events (profile_id, effective_at, id);
CREATE INDEX IF NOT EXISTS membership_status_events_status_time_idx
  ON public.membership_status_events (status, effective_at);

CREATE OR REPLACE FUNCTION public.capture_membership_status_event()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_source text;
BEGIN
  IF TG_OP = 'INSERT'
     OR NEW.membership_status IS DISTINCT FROM OLD.membership_status
     OR NEW.membership_tier IS DISTINCT FROM OLD.membership_tier THEN
    v_source := CASE
      WHEN current_setting('request.jwt.claim.role', true) = 'service_role' THEN 'service_role'
      WHEN auth.uid() IS NOT NULL THEN 'admin_or_system'
      ELSE 'database'
    END;

    INSERT INTO public.membership_status_events
      (profile_id, status, membership_tier, effective_at, source, is_baseline)
    VALUES
      (NEW.id, COALESCE(NEW.membership_status, 'none'),
       COALESCE(NEW.membership_tier, 'none'), now(), v_source, false);
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS capture_membership_status_event ON public.profiles;
CREATE TRIGGER capture_membership_status_event
  AFTER INSERT OR UPDATE OF membership_status, membership_tier ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.capture_membership_status_event();

-- A truthful current-state baseline. Its timestamp is now(), never the member's
-- join date. Reporting excludes baseline rows from retention starts/new joins.
INSERT INTO public.membership_status_events
  (profile_id, status, membership_tier, effective_at, source, is_baseline)
SELECT p.id, p.membership_status, p.membership_tier, now(),
       'reporting_migration_baseline', true
FROM public.profiles p
WHERE NOT EXISTS (
  SELECT 1 FROM public.membership_status_events e WHERE e.profile_id = p.id
);

CREATE OR REPLACE VIEW public.reporting_membership_intervals AS
SELECT
  e.profile_id,
  e.status,
  e.membership_tier,
  e.effective_at AS starts_at,
  lead(e.effective_at) OVER (
    PARTITION BY e.profile_id ORDER BY e.effective_at, e.id
  ) AS ends_at,
  e.is_baseline,
  e.source
FROM public.membership_status_events e;

REVOKE ALL ON public.reporting_membership_intervals FROM PUBLIC, anon, authenticated;

-- ---------------------------------------------------------------------------
-- 3. Privacy-safe journal engagement events
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.journal_field_activity_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  week_number integer NOT NULL CHECK (week_number BETWEEN 1 AND 52),
  track text NOT NULL CHECK (track IN ('Adult','Teen','Child')),
  field_key text NOT NULL CHECK (field_key IN (
    'video_question_1_response',
    'video_question_2_response',
    'reflection_answer',
    'activity_response',
    'personal_notes',
    'life_group_notes',
    'weekly_intention'
  )),
  event text NOT NULL CHECK (event IN ('completed','cleared')),
  occurred_at timestamptz NOT NULL DEFAULT now(),
  is_baseline boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.journal_field_activity_events ENABLE ROW LEVEL SECURITY;
-- Intentionally no table policies: even metadata is available to Admin only
-- through aggregate RPCs. No response values are stored here.

CREATE INDEX IF NOT EXISTS journal_field_activity_profile_week_idx
  ON public.journal_field_activity_events (profile_id, week_number, track, field_key, occurred_at, id);
CREATE INDEX IF NOT EXISTS journal_field_activity_time_idx
  ON public.journal_field_activity_events (occurred_at, track, event);

CREATE TABLE IF NOT EXISTS public.journal_session_activity (
  profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  week_number integer NOT NULL CHECK (week_number BETWEEN 1 AND 52),
  track text NOT NULL CHECK (track = 'Adult'),
  first_opened_at timestamptz NOT NULL DEFAULT now(),
  last_opened_at timestamptz NOT NULL DEFAULT now(),
  open_count integer NOT NULL DEFAULT 1 CHECK (open_count > 0),
  PRIMARY KEY (profile_id, week_number, track)
);

ALTER TABLE public.journal_session_activity ENABLE ROW LEVEL SECURITY;
-- No direct reads. Members record their own open through the narrow RPC below;
-- Admin receives only aggregate funnel counts.

CREATE INDEX IF NOT EXISTS journal_session_activity_time_idx
  ON public.journal_session_activity (last_opened_at, week_number);

CREATE OR REPLACE FUNCTION public.record_my_journal_open(p_week integer)
RETURNS void
LANGUAGE plpgsql VOLATILE SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_profile_id uuid;
BEGIN
  IF p_week NOT BETWEEN 1 AND 52 OR NOT public.can_access_track('Adult') THEN
    RAISE EXCEPTION 'not authorized';
  END IF;
  v_profile_id := public.current_profile_id();
  IF v_profile_id IS NULL THEN RAISE EXCEPTION 'profile not found'; END IF;

  INSERT INTO public.journal_session_activity
    (profile_id, week_number, track, first_opened_at, last_opened_at, open_count)
  VALUES (v_profile_id, p_week, 'Adult', now(), now(), 1)
  ON CONFLICT (profile_id, week_number, track) DO UPDATE
    SET last_opened_at = EXCLUDED.last_opened_at,
        open_count = public.journal_session_activity.open_count + 1;
END;
$$;

REVOKE ALL ON FUNCTION public.record_my_journal_open(integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.record_my_journal_open(integer) TO authenticated;

CREATE OR REPLACE FUNCTION public.reporting_has_meaningful_response(p_value text)
RETURNS boolean
LANGUAGE sql IMMUTABLE PARALLEL SAFE
AS $$
  SELECT NULLIF(btrim(COALESCE(p_value, '')), '') IS NOT NULL
    AND lower(btrim(COALESCE(p_value, ''))) NOT IN (
      '[placeholder]', 'placeholder', 'type here', 'write here', 'enter response here'
    );
$$;

CREATE OR REPLACE FUNCTION public.capture_journal_field_activity()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_field record;
  v_old_complete boolean;
  v_new_complete boolean;
BEGIN
  -- Teen and Child tracks are paper-only. This capture is intentionally Adult
  -- only even if legacy under-18 rows remain in lesson_journal.
  IF NEW.track <> 'Adult' THEN
    RETURN NEW;
  END IF;

  FOR v_field IN
    SELECT * FROM (VALUES
      ('video_question_1_response', CASE WHEN TG_OP = 'UPDATE' THEN OLD.video_question_1_response END, NEW.video_question_1_response),
      ('video_question_2_response', CASE WHEN TG_OP = 'UPDATE' THEN OLD.video_question_2_response END, NEW.video_question_2_response),
      ('reflection_answer',         CASE WHEN TG_OP = 'UPDATE' THEN OLD.reflection_answer END,         NEW.reflection_answer),
      ('activity_response',         CASE WHEN TG_OP = 'UPDATE' THEN OLD.activity_response END,         NEW.activity_response),
      ('personal_notes',            CASE WHEN TG_OP = 'UPDATE' THEN OLD.personal_notes END,            NEW.personal_notes),
      ('life_group_notes',          CASE WHEN TG_OP = 'UPDATE' THEN OLD.life_group_notes END,          NEW.life_group_notes),
      ('weekly_intention',          CASE WHEN TG_OP = 'UPDATE' THEN OLD.weekly_intention END,          NEW.weekly_intention)
    ) AS fields(field_key, old_value, new_value)
  LOOP
    v_old_complete := public.reporting_has_meaningful_response(v_field.old_value);
    v_new_complete := public.reporting_has_meaningful_response(v_field.new_value);
    IF v_old_complete IS DISTINCT FROM v_new_complete THEN
      INSERT INTO public.journal_field_activity_events
        (profile_id, week_number, track, field_key, event, occurred_at, is_baseline)
      VALUES
        (NEW.profile_id, NEW.week_number, NEW.track, v_field.field_key,
         CASE WHEN v_new_complete THEN 'completed' ELSE 'cleared' END,
         now(), false);
    END IF;
  END LOOP;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS capture_journal_field_activity ON public.lesson_journal;
CREATE TRIGGER capture_journal_field_activity
  AFTER INSERT OR UPDATE ON public.lesson_journal
  FOR EACH ROW EXECUTE FUNCTION public.capture_journal_field_activity();

-- Baseline only records fields currently non-empty. It is useful for present
-- session completion, but excluded from time-of-entry trends.
INSERT INTO public.journal_field_activity_events
  (profile_id, week_number, track, field_key, event, occurred_at, is_baseline)
SELECT lj.profile_id, lj.week_number, lj.track, f.field_key, 'completed', now(), true
FROM public.lesson_journal lj
CROSS JOIN LATERAL (VALUES
  ('video_question_1_response', lj.video_question_1_response),
  ('video_question_2_response', lj.video_question_2_response),
  ('reflection_answer', lj.reflection_answer),
  ('activity_response', lj.activity_response),
  ('personal_notes', lj.personal_notes),
  ('life_group_notes', lj.life_group_notes),
  ('weekly_intention', lj.weekly_intention)
) AS f(field_key, field_value)
WHERE lj.track = 'Adult'
  AND public.reporting_has_meaningful_response(f.field_value)
  AND NOT EXISTS (
    SELECT 1
    FROM public.journal_field_activity_events e
    WHERE e.profile_id = lj.profile_id
      AND e.week_number = lj.week_number
      AND e.track = lj.track
      AND e.field_key = f.field_key
  );

CREATE OR REPLACE VIEW public.reporting_journal_field_state AS
SELECT profile_id, week_number, track, field_key, event, occurred_at, is_baseline
FROM (
  SELECT e.*,
         row_number() OVER (
           PARTITION BY e.profile_id, e.week_number, e.track, e.field_key
           ORDER BY e.occurred_at DESC, e.id DESC
         ) AS row_rank
  FROM public.journal_field_activity_events e
) ranked
WHERE row_rank = 1;

REVOKE ALL ON public.reporting_journal_field_state FROM PUBLIC, anon, authenticated;

-- ---------------------------------------------------------------------------
-- 4. Subscription amount snapshots for reliable forward MRR
-- ---------------------------------------------------------------------------
ALTER TABLE public.subscriptions
  ADD COLUMN IF NOT EXISTS mrr_cents integer,
  ADD COLUMN IF NOT EXISTS currency text;

CREATE INDEX IF NOT EXISTS subscriptions_reporting_idx
  ON public.subscriptions (status, tier, household_id, mrr_cents);

-- ---------------------------------------------------------------------------
-- 5. Configurable operational thresholds and explicit coverage marker
-- ---------------------------------------------------------------------------
INSERT INTO public.app_settings (key, value) VALUES
  ('reporting_history_started_at', now()::text),
  ('reporting_attendance_target', '0.65'),
  ('reporting_at_risk_recent_misses', '2'),
  ('reporting_at_risk_six_week_rate', '0.50'),
  ('reporting_at_risk_attendance_days', '21'),
  ('reporting_at_risk_journal_weeks', '3')
ON CONFLICT (key) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 6. Central definitions exposed to the Admin UI
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_reporting_metric_definitions()
RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin'::app_role) THEN
    RAISE EXCEPTION 'not authorized';
  END IF;

  RETURN jsonb_build_object(
    'active_member', 'A profile whose effective membership status is active or trialing. This matches the paid-content access gate; past_due is reported separately.',
    'paying_member', 'A profile or household covered by a Stripe subscription whose current status is active. Trialing is not counted as paying.',
    'eligible_session', 'A non-cancelled scheduled session on or after reporting capture, in the member''s track and location, occurring while their membership status interval is active or trialing.',
    'attended', 'At least one valid check_ins record for the profile and scheduled session. Duplicate check-ins count once.',
    'missed', 'An eligible session with no valid check-in. A person is never missed before membership starts, after it ends, at another track/location, or for a cancelled session.',
    'attendance_rate', 'Distinct eligible sessions attended divided by eligible sessions available.',
    'return_after_miss', 'Missed eligible-session outcomes whose next eligible session was attended, divided by misses with a subsequent eligible session.',
    'journal_entry', 'A persisted Adult-track journal field changing from empty to a meaningful non-empty response. No response content is copied into reporting.',
    'journal_completion', 'Currently completed available Adult journal fields divided by fields available for that member/week. Teen and Child are paper-only and display N/A.',
    'retention', 'Members with a non-baseline active start who are still active at the stated duration, divided only by starts old enough to reach that duration.',
    'churn', 'Members transitioning from active/trialing to a terminal lapsed/none state during a period divided by active/trialing members at the beginning. Paused and past_due remain visible but are not cancellation churn.',
    'historical_coverage', 'Status and journal transition history is reliable from reporting_history_started_at. Migration baselines are current-state facts, not backdated history.'
  );
END;
$$;

REVOKE ALL ON FUNCTION public.admin_reporting_metric_definitions() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_reporting_metric_definitions() TO authenticated;
