-- Notion lesson pull — per-track lesson titles + weekly themes.
--
-- Generated by scripts/pull-notion-lessons.mjs from the 52-Week
-- Curriculum Notion exports (the founder's working source). Re-run the
-- script after each Notion edit pass and commit the new migration.
--
-- Titles only: the full lesson bodies stay in mindcast_live_sessions /
-- the per-week lesson pulls. The public curriculum page lists these
-- per-track titles, so this is the fix for stale room titles.

UPDATE public.curriculum_weeks SET
  adult_video_title = 'What Are You Actually Receiving?',
  teen_video_title  = 'Who''s Actually Talking?',
  kids_title        = 'Finding Your Station',
  weekly_theme      = 'The Signal and the Noise'
WHERE week_number = 1;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Reading the Code You Were Given',
  teen_video_title  = 'The Playlist You Didn''t Choose',
  kids_title        = 'What''s in Your Backpack?'
WHERE week_number = 2;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Finding the Gap',
  teen_video_title  = 'The Chat You''re Not Reading',
  kids_title        = 'The Pause Button',
  weekly_theme      = 'The Pattern Interrupt'
WHERE week_number = 3;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Turning the Diagnostics Back On',
  teen_video_title  = 'Reading the Data Your Body Collects',
  kids_title        = 'Your Feelings Weather Station',
  weekly_theme      = 'What Your Body Is Telling You'
WHERE week_number = 4;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Recalibrating the Lens',
  teen_video_title  = 'The Comparison Trap and the Real Mirror',
  kids_title        = 'The True Mirror',
  weekly_theme      = 'The Mirror — How We See Ourselves'
WHERE week_number = 5;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Getting Off the Loop',
  teen_video_title  = 'The Race With the Moving Finish Line',
  kids_title        = 'Your Own Puzzle',
  weekly_theme      = 'The Comparison Loop'
WHERE week_number = 6;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Naming the Judge',
  teen_video_title  = 'Introducing the Heckler',
  kids_title        = 'Meeting the Gremlin',
  weekly_theme      = 'The Inner Critic'
WHERE week_number = 7;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Reading the Data Stream',
  teen_video_title  = 'Optimising the Notification System',
  kids_title        = 'The Feelings Iceberg',
  weekly_theme      = 'Beneath the Surface — Emotions as Data'
WHERE week_number = 8;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'The Kintsugi Audit',
  teen_video_title  = 'The Update Nobody Installed on Purpose',
  kids_title        = 'The Stone in Your Pocket',
  weekly_theme      = 'The Wounds We Carry'
WHERE week_number = 9;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Frontend and Backend',
  teen_video_title  = 'Which One Is Actually You?',
  kids_title        = 'The Real Face and the Pretend Faces',
  weekly_theme      = 'The Masks We Wear'
WHERE week_number = 10;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Calibrating the Sensor',
  teen_video_title  = 'Turning Down the Projector',
  kids_title        = 'Walking Around the Picture',
  weekly_theme      = 'Seeing Others Clearly'
WHERE week_number = 11;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Mapping the Loops',
  teen_video_title  = 'Understanding Autopilot',
  kids_title        = 'The Habit Path',
  weekly_theme      = 'The Habit Loop — How We Got Here'
WHERE week_number = 12;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'The Audit Is Complete',
  teen_video_title  = 'The Diagnostic Is Complete',
  kids_title        = 'Looking at Our Full Backpack',
  weekly_theme      = 'Integration — What We Now See'
WHERE week_number = 13;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'You Are the Authority',
  teen_video_title  = 'Admin Access Granted',
  kids_title        = 'Your Own GO Button',
  weekly_theme      = 'Admin Access Granted'
WHERE week_number = 14;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Default Settings and Custom Configuration',
  teen_video_title  = 'Default Settings',
  kids_title        = 'My Own Picture',
  weekly_theme      = 'Letting Go of Who You Were Supposed to Be'
WHERE week_number = 15;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Completing the Process',
  teen_video_title  = 'Closing the Background Apps',
  kids_title        = 'Putting Down the Hot Rock',
  weekly_theme      = 'The Forgiveness Loop'
WHERE week_number = 16;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Clearing the Cache',
  teen_video_title  = 'Closing the 2am Replay',
  kids_title        = 'Say Sorry and Keep Going',
  weekly_theme      = 'Forgiving Yourself'
WHERE week_number = 17;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Building the Better Architecture',
  teen_video_title  = 'Building the Track',
  kids_title        = 'Making the Kind Voice Louder',
  weekly_theme      = 'Training the Inner Coach'
WHERE week_number = 18;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Reorienting the Function',
  teen_video_title  = 'The Battery Drain',
  kids_title        = 'Kind vs. People-Pleasing',
  weekly_theme      = 'Breaking the People-Pleasing Pattern'
WHERE week_number = 19;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Uninstalling the Scarcity Operating System',
  teen_video_title  = 'The Resource Monitor',
  kids_title        = 'The Things That Don''t Run Out',
  weekly_theme      = 'Unlearning Scarcity — There Is Enough'
WHERE week_number = 20;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Structural Assessment',
  teen_video_title  = 'Auditing the Relationship Code',
  kids_title        = 'The Gifts People Give Us',
  weekly_theme      = 'The Relationships That Shaped You'
WHERE week_number = 21;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Updating the Security System',
  teen_video_title  = 'Firewall Settings',
  kids_title        = 'The Shield With a Door',
  weekly_theme      = 'Setting Down the Armour'
WHERE week_number = 22;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Completing the Close',
  teen_video_title  = 'Making Space for an Ending',
  kids_title        = 'The Autumn Before Spring',
  weekly_theme      = 'Grief and Growth — What Endings Make Possible'
WHERE week_number = 23;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Calibrating the Threat Sensor',
  teen_video_title  = 'Updating the Alarm System',
  kids_title        = 'The Toast Alarm vs. The Real Fire',
  weekly_theme      = 'Calibrating Fear — From Threat to Signal'
WHERE week_number = 24;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Writing the Upgrade',
  teen_video_title  = 'Writing the Update',
  kids_title        = 'Updating the Photo Album',
  weekly_theme      = 'The Stories That No Longer Serve'
WHERE week_number = 25;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Cleared Ground',
  teen_video_title  = 'What You''ve Put Down',
  kids_title        = 'Putting Down the Heavy Things',
  weekly_theme      = 'Integration — Cleared Ground'
WHERE week_number = 26;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Configuration Begins',
  teen_video_title  = 'The First Brick',
  kids_title        = 'Who Are You Building?',
  weekly_theme      = 'The New Foundation — Choosing Who You Become'
WHERE week_number = 27;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Setting the Priority Hierarchy',
  teen_video_title  = 'Opening the Settings Menu',
  kids_title        = 'Your Inner Compass'
WHERE week_number = 28;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Installing the New Architecture',
  teen_video_title  = 'Designing the Practice',
  kids_title        = 'Watering Your Garden'
WHERE week_number = 29;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'The Hardware Layer',
  teen_video_title  = 'Charging the Hardware',
  kids_title        = 'Charging Your Superhero Suit'
WHERE week_number = 30;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Designing the Social Environment',
  teen_video_title  = 'Your Operating Environment',
  kids_title        = 'Growing Friends',
  weekly_theme      = 'Designing the Social Environment'
WHERE week_number = 31;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'The Daily Soundtrack',
  teen_video_title  = 'Redesigning the Soundtrack',
  kids_title        = 'Finding Your Power Phrases',
  weekly_theme      = 'Redesigning the Soundtrack'
WHERE week_number = 32;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Designing the Container',
  teen_video_title  = 'Designing the Container',
  kids_title        = 'Your Personal Rhythm',
  weekly_theme      = 'Creating Structure That Serves You'
WHERE week_number = 33;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Scheduled Maintenance',
  teen_video_title  = 'The Recovery Protocol',
  kids_title        = 'Rest Is a Superpower',
  weekly_theme      = 'Rest as a Practice, Not a Reward'
WHERE week_number = 34;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Restoring the Output Channel',
  teen_video_title  = 'Making Without Judging',
  kids_title        = 'The Joy of Making',
  weekly_theme      = 'Creativity and Expression'
WHERE week_number = 35;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Orienting Toward What Is Genuinely Yours',
  teen_video_title  = 'Finding the Direction',
  kids_title        = 'Your Special Puzzle Piece',
  weekly_theme      = 'Purpose — What You''re Here For'
WHERE week_number = 36;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Rebuilding the Resource Relationship',
  teen_video_title  = 'What You''ve Inherited About Resources',
  kids_title        = 'What We Have and What We Share',
  weekly_theme      = 'Money, Resources and Choice'
WHERE week_number = 37;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Building the Ecology of Growth',
  teen_video_title  = 'Building Real Connection',
  kids_title        = 'Being Part of Something Bigger',
  weekly_theme      = 'The Community You Build'
WHERE week_number = 38;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'The Foundation Is Laid',
  teen_video_title  = 'What Has Been Built',
  kids_title        = 'Look What We''ve Built!',
  weekly_theme      = 'Integration — What Is Actually Working'
WHERE week_number = 39;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'The Turn Outward',
  teen_video_title  = 'Pointing the Torch Outward',
  kids_title        = 'Sharing the Treasure',
  weekly_theme      = 'From Self-Development to Contribution'
WHERE week_number = 40;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'The Test of Understanding',
  teen_video_title  = 'Learning by Giving It Away',
  kids_title        = 'Becoming a Teacher',
  weekly_theme      = 'Explaining What You Know'
WHERE week_number = 41;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Going Live',
  teen_video_title  = 'Closing the Gap',
  kids_title        = 'The Real You, All the Way',
  weekly_theme      = 'Authenticity With Privacy'
WHERE week_number = 42;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Values Under Load',
  teen_video_title  = 'The Pressure Test',
  kids_title        = 'Compass in the Storm',
  weekly_theme      = 'Living Your Values Under Pressure'
WHERE week_number = 43;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'The Interface Layer',
  teen_video_title  = 'Needs, Not Positions',
  kids_title        = 'The Gentle Untangle',
  weekly_theme      = 'Conflict as a Communication Practice'
WHERE week_number = 44;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Hands Open',
  teen_video_title  = 'Open Hands',
  kids_title        = 'Gifts That Grow',
  weekly_theme      = 'Open Hands — Generosity With Limits'
WHERE week_number = 45;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'The Stable Baseline',
  teen_video_title  = 'Starting From Here',
  kids_title        = 'Noticing the Garden',
  weekly_theme      = 'Starting From Here — Defining Enough'
WHERE week_number = 46;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Trusting the Process',
  teen_video_title  = 'Compound Interest for a Person',
  kids_title        = 'Keep Watering the Plant',
  weekly_theme      = 'The Long Game — Persistence With Feedback'
WHERE week_number = 47;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Positive Externalities',
  teen_video_title  = 'One Question',
  kids_title        = 'Being a Sunshine Person',
  weekly_theme      = 'The Quality of Everyday Encounters'
WHERE week_number = 48;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'What Are You Actually Building?',
  teen_video_title  = 'What Do You Want Them to Say?',
  kids_title        = 'Your Ripples',
  weekly_theme      = 'What Repeated Behaviour Builds'
WHERE week_number = 49;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Deliberate Attention',
  teen_video_title  = 'Training the Noticing Muscle',
  kids_title        = 'Training the Gratitude Camera',
  weekly_theme      = 'Deliberate Attention and Gratitude'
WHERE week_number = 50;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'The Practice That Keeps Practising',
  teen_video_title  = 'The Practice That Keeps Practising',
  kids_title        = 'The Adventure Continues',
  weekly_theme      = 'Maintenance and Ownership'
WHERE week_number = 51;

UPDATE public.curriculum_weeks SET
  adult_video_title = 'Ending Well',
  teen_video_title  = 'The Return With Gifts',
  kids_title        = 'The Best Kind of Ending',
  weekly_theme      = 'Ending Well — Review, Ownership and Choice'
WHERE week_number = 52;
