-- MINDCAST monthly investor updates.
--
-- The report builder consumes the same admin_reporting_dashboard RPC used by
-- Admin Insights. Narrative copy and metric selections stay editable while a
-- report is Draft/Ready; Sent rows retain the exact HTML, text and metric JSON
-- delivered to investors. No member-level or journal-content data is stored.

-- ---------------------------------------------------------------------------
-- 1. Future-safe billing history (current subscriptions is only a mirror)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.subscription_reporting_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription_id uuid NOT NULL REFERENCES public.subscriptions(id) ON DELETE CASCADE,
  profile_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  household_id uuid REFERENCES public.households(id) ON DELETE SET NULL,
  status text NOT NULL,
  mrr_cents integer,
  currency text,
  effective_at timestamptz NOT NULL DEFAULT now(),
  is_baseline boolean NOT NULL DEFAULT false,
  source text NOT NULL DEFAULT 'subscription_update',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.subscription_reporting_events ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS subscription_reporting_events_subscription_time_idx
  ON public.subscription_reporting_events (subscription_id, effective_at, id);
CREATE INDEX IF NOT EXISTS subscription_reporting_events_status_time_idx
  ON public.subscription_reporting_events (status, effective_at);

CREATE OR REPLACE FUNCTION public.capture_subscription_reporting_event()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT'
     OR NEW.status IS DISTINCT FROM OLD.status
     OR NEW.mrr_cents IS DISTINCT FROM OLD.mrr_cents
     OR NEW.currency IS DISTINCT FROM OLD.currency
     OR NEW.profile_id IS DISTINCT FROM OLD.profile_id
     OR NEW.household_id IS DISTINCT FROM OLD.household_id THEN
    INSERT INTO public.subscription_reporting_events (
      subscription_id, profile_id, household_id, status, mrr_cents, currency,
      effective_at, is_baseline, source
    ) VALUES (
      NEW.id, NEW.profile_id, NEW.household_id, NEW.status, NEW.mrr_cents,
      NEW.currency, now(), false,
      CASE WHEN current_setting('request.jwt.claim.role', true) = 'service_role'
        THEN 'stripe_webhook' ELSE 'subscription_update' END
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS capture_subscription_reporting_event ON public.subscriptions;
CREATE TRIGGER capture_subscription_reporting_event
  AFTER INSERT OR UPDATE OF status, mrr_cents, currency, profile_id, household_id
  ON public.subscriptions
  FOR EACH ROW EXECUTE FUNCTION public.capture_subscription_reporting_event();

-- This is an honest current-state baseline, not reconstructed history.
INSERT INTO public.subscription_reporting_events (
  subscription_id, profile_id, household_id, status, mrr_cents, currency,
  effective_at, is_baseline, source
)
SELECT s.id, s.profile_id, s.household_id, s.status, s.mrr_cents, s.currency,
       now(), true, 'investor_reporting_baseline'
FROM public.subscriptions s
WHERE NOT EXISTS (
  SELECT 1 FROM public.subscription_reporting_events e
  WHERE e.subscription_id = s.id
);

INSERT INTO public.app_settings (key, value)
VALUES ('investor_billing_history_started_at', now()::text)
ON CONFLICT (key) DO NOTHING;

CREATE OR REPLACE VIEW public.reporting_subscription_intervals AS
SELECT
  e.subscription_id,
  e.profile_id,
  e.household_id,
  e.status,
  e.mrr_cents,
  e.currency,
  e.effective_at AS starts_at,
  lead(e.effective_at) OVER (
    PARTITION BY e.subscription_id ORDER BY e.effective_at, e.id
  ) AS ends_at,
  e.is_baseline,
  e.source
FROM public.subscription_reporting_events e;

REVOKE ALL ON public.reporting_subscription_intervals FROM PUBLIC, anon, authenticated;

-- ---------------------------------------------------------------------------
-- 2. Report records, priorities and audit history
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.investor_reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  report_month date NOT NULL,
  version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  revision_of uuid REFERENCES public.investor_reports(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'ready', 'sent', 'archived')),
  subject text NOT NULL DEFAULT '',
  preheader text NOT NULL DEFAULT '',
  headline text NOT NULL DEFAULT '',
  good text NOT NULL DEFAULT '',
  bad text NOT NULL DEFAULT '',
  ugly text NOT NULL DEFAULT '',
  learned_headline text NOT NULL DEFAULT '',
  learned_body text NOT NULL DEFAULT '',
  customer_quote text NOT NULL DEFAULT '',
  customer_quote_attribution text NOT NULL DEFAULT '',
  behaviour_change_numerator integer CHECK (behaviour_change_numerator >= 0),
  behaviour_change_denominator integer CHECK (behaviour_change_denominator > 0),
  behaviour_change_period text NOT NULL DEFAULT '',
  behaviour_change_notes text NOT NULL DEFAULT '',
  family_signal_label text NOT NULL DEFAULT '',
  family_signal_numerator integer CHECK (family_signal_numerator >= 0),
  family_signal_denominator integer CHECK (family_signal_denominator > 0),
  family_signal_notes text NOT NULL DEFAULT '',
  one_ask text NOT NULL DEFAULT '',
  selected_metric_ids text[] NOT NULL DEFAULT ARRAY[
    'active_paying_members', 'mrr', 'net_member_growth',
    'eight_week_retention', 'weekly_attendance', 'journal_completion',
    'referral_rate', 'active_households'
  ]::text[],
  metrics_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  metric_definition_version text NOT NULL DEFAULT 'admin-reporting-v1',
  metrics_refreshed_at timestamptz,
  generated_html text,
  generated_text text,
  sent_at timestamptz,
  sent_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT investor_reports_month_start CHECK (
    report_month = date_trunc('month', report_month)::date
  ),
  CONSTRAINT investor_reports_behaviour_sample CHECK (
    behaviour_change_numerator IS NULL
    OR behaviour_change_denominator IS NULL
    OR behaviour_change_numerator <= behaviour_change_denominator
  ),
  CONSTRAINT investor_reports_family_sample CHECK (
    family_signal_numerator IS NULL
    OR family_signal_denominator IS NULL
    OR family_signal_numerator <= family_signal_denominator
  ),
  CONSTRAINT investor_reports_sent_snapshot_required CHECK (
    status NOT IN ('sent','archived')
    OR (
      metrics_snapshot <> '{}'::jsonb
      AND NULLIF(btrim(generated_html), '') IS NOT NULL
      AND NULLIF(btrim(generated_text), '') IS NOT NULL
      AND sent_at IS NOT NULL
    )
  ),
  UNIQUE (report_month, version)
);

CREATE INDEX IF NOT EXISTS investor_reports_month_status_idx
  ON public.investor_reports (report_month DESC, version DESC, status);

CREATE TABLE IF NOT EXISTS public.investor_report_priorities (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL REFERENCES public.investor_reports(id) ON DELETE CASCADE,
  position integer NOT NULL CHECK (position BETWEEN 1 AND 10),
  objective text NOT NULL DEFAULT '',
  target text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'planned'
    CHECK (status IN ('planned', 'complete', 'moved', 'not_met')),
  outcome text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (report_id, position)
);

CREATE TABLE IF NOT EXISTS public.investor_report_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id uuid NOT NULL REFERENCES public.investor_reports(id) ON DELETE CASCADE,
  event text NOT NULL CHECK (event IN (
    'created', 'saved', 'metrics_refreshed', 'ready', 'sent', 'archived',
    'revision_created', 'test_sent'
  )),
  actor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS investor_report_audit_report_time_idx
  ON public.investor_report_audit (report_id, occurred_at DESC);

CREATE TABLE IF NOT EXISTS public.investor_report_deliveries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  report_id uuid REFERENCES public.investor_reports(id) ON DELETE SET NULL,
  recipient_email text NOT NULL,
  recipient_count integer NOT NULL DEFAULT 1 CHECK (recipient_count > 0),
  subject text NOT NULL,
  sender text NOT NULL,
  is_test boolean NOT NULL DEFAULT true,
  provider_message_id text,
  status text NOT NULL DEFAULT 'sent' CHECK (status IN ('sent', 'failed')),
  error text,
  sent_html text NOT NULL,
  sent_text text NOT NULL,
  sent_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  sent_at timestamptz NOT NULL DEFAULT now()
);

-- A future subscriber list without open/click tracking. There is no existing
-- investor CRM table in the project; this table is intentionally not wired to
-- bulk-send UI in this release.
CREATE TABLE IF NOT EXISTS public.investor_update_contacts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  first_name text NOT NULL DEFAULT '',
  last_name text NOT NULL DEFAULT '',
  email text NOT NULL UNIQUE,
  organisation text NOT NULL DEFAULT '',
  contact_type text NOT NULL DEFAULT 'investor',
  source_context text NOT NULL DEFAULT '',
  is_active boolean NOT NULL DEFAULT true,
  notes text NOT NULL DEFAULT '',
  last_update_sent_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.investor_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.investor_report_priorities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.investor_report_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.investor_report_deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.investor_update_contacts ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.investor_reports TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.investor_report_priorities TO authenticated;
GRANT SELECT, INSERT ON public.investor_report_audit TO authenticated;
GRANT SELECT ON public.investor_report_deliveries TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.investor_update_contacts TO authenticated;

DROP POLICY IF EXISTS investor_reports_admin_all ON public.investor_reports;
CREATE POLICY investor_reports_admin_all ON public.investor_reports
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::app_role))
  WITH CHECK (public.has_role(auth.uid(), 'admin'::app_role));

DROP POLICY IF EXISTS investor_priorities_admin_all ON public.investor_report_priorities;
CREATE POLICY investor_priorities_admin_all ON public.investor_report_priorities
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::app_role))
  WITH CHECK (public.has_role(auth.uid(), 'admin'::app_role));

DROP POLICY IF EXISTS investor_audit_admin_read ON public.investor_report_audit;
CREATE POLICY investor_audit_admin_read ON public.investor_report_audit
  FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::app_role));

DROP POLICY IF EXISTS investor_audit_admin_insert ON public.investor_report_audit;
CREATE POLICY investor_audit_admin_insert ON public.investor_report_audit
  FOR INSERT TO authenticated
  WITH CHECK (public.has_role(auth.uid(), 'admin'::app_role));

DROP POLICY IF EXISTS investor_deliveries_admin_read ON public.investor_report_deliveries;
CREATE POLICY investor_deliveries_admin_read ON public.investor_report_deliveries
  FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::app_role));

DROP POLICY IF EXISTS investor_contacts_admin_all ON public.investor_update_contacts;
CREATE POLICY investor_contacts_admin_all ON public.investor_update_contacts
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::app_role))
  WITH CHECK (public.has_role(auth.uid(), 'admin'::app_role));

DROP TRIGGER IF EXISTS update_investor_reports_updated_at ON public.investor_reports;
CREATE TRIGGER update_investor_reports_updated_at
  BEFORE UPDATE ON public.investor_reports
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_investor_priorities_updated_at ON public.investor_report_priorities;
CREATE TRIGGER update_investor_priorities_updated_at
  BEFORE UPDATE ON public.investor_report_priorities
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_investor_contacts_updated_at ON public.investor_update_contacts;
CREATE TRIGGER update_investor_contacts_updated_at
  BEFORE UPDATE ON public.investor_update_contacts
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE OR REPLACE FUNCTION public.protect_sent_investor_report()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'DELETE' AND OLD.status IN ('sent', 'archived') THEN
    RAISE EXCEPTION 'Sent investor reports are immutable; create a revision instead.';
  END IF;

  IF TG_OP = 'UPDATE' AND OLD.status IN ('sent', 'archived') THEN
    IF NOT (
      OLD.status = 'sent'
      AND NEW.status = 'archived'
      AND (to_jsonb(NEW) - ARRAY['status','updated_at','updated_by'])
          = (to_jsonb(OLD) - ARRAY['status','updated_at','updated_by'])
    ) THEN
      RAISE EXCEPTION 'Sent investor reports are immutable; create a revision instead.';
    END IF;
  END IF;
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

DROP TRIGGER IF EXISTS protect_sent_investor_report ON public.investor_reports;
CREATE TRIGGER protect_sent_investor_report
  BEFORE UPDATE OR DELETE ON public.investor_reports
  FOR EACH ROW EXECUTE FUNCTION public.protect_sent_investor_report();

CREATE OR REPLACE FUNCTION public.protect_sent_investor_priority()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_report_id uuid;
  v_status text;
BEGIN
  v_report_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.report_id ELSE NEW.report_id END;
  SELECT status INTO v_status FROM public.investor_reports WHERE id = v_report_id;
  IF v_status IN ('sent', 'archived') THEN
    RAISE EXCEPTION 'Priorities on Sent investor reports are immutable; create a revision instead.';
  END IF;
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

DROP TRIGGER IF EXISTS protect_sent_investor_priority ON public.investor_report_priorities;
CREATE TRIGGER protect_sent_investor_priority
  BEFORE INSERT OR UPDATE OR DELETE ON public.investor_report_priorities
  FOR EACH ROW EXECUTE FUNCTION public.protect_sent_investor_priority();

-- ---------------------------------------------------------------------------
-- 3. Shared monthly metric payload
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.admin_investor_billing_snapshot(
  p_as_of timestamptz,
  p_period_start timestamptz DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_capture_at timestamptz;
  v_result jsonb;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin'::app_role) THEN
    RAISE EXCEPTION 'not authorized';
  END IF;

  SELECT value::timestamptz INTO v_capture_at
  FROM public.app_settings
  WHERE key = 'investor_billing_history_started_at';

  IF v_capture_at IS NULL OR p_as_of < v_capture_at THEN
    RETURN jsonb_build_object(
      'available', false,
      'capture_started_at', v_capture_at,
      'reason', 'Billing history was not captured at this reporting cutoff.'
    );
  END IF;

  WITH latest AS (
    SELECT DISTINCT ON (subscription_id)
      subscription_id, profile_id, household_id, status, mrr_cents, currency
    FROM public.subscription_reporting_events
    WHERE effective_at <= p_as_of
    ORDER BY subscription_id, effective_at DESC, id DESC
  ),
  active_subscriptions AS (
    SELECT * FROM latest WHERE status = 'active'
  ),
  active_members AS (
    SELECT DISTINCT d.profile_id
    FROM public.reporting_member_dimension d
    JOIN public.reporting_membership_intervals mi
      ON mi.profile_id = d.profile_id
     AND mi.status IN ('active','trialing')
     AND mi.starts_at <= p_as_of
     AND (mi.ends_at IS NULL OR mi.ends_at > p_as_of)
    JOIN active_subscriptions s
      ON s.profile_id = d.profile_id
      OR (s.household_id IS NOT NULL AND s.household_id = d.household_id)
  ),
  transitions AS (
    SELECT e.*,
      lag(status) OVER (
        PARTITION BY subscription_id ORDER BY effective_at, id
      ) AS previous_status
    FROM public.subscription_reporting_events e
  ),
  resolved_trials AS (
    SELECT * FROM transitions
    WHERE p_period_start IS NOT NULL
      AND effective_at >= p_period_start
      AND effective_at <= p_as_of
      AND previous_status = 'trialing'
      AND status <> 'trialing'
  )
  SELECT jsonb_build_object(
    'available', true,
    'capture_started_at', v_capture_at,
    'as_of', p_as_of,
    'active_subscriptions', (SELECT count(*) FROM active_subscriptions),
    'active_paying_members', (SELECT count(*) FROM active_members),
    'mrr_cents', (
      SELECT CASE
        WHEN count(*) = 0 THEN 0
        WHEN count(mrr_cents) <> count(*) OR count(DISTINCT currency) <> 1 THEN NULL
        ELSE sum(mrr_cents)
      END
      FROM active_subscriptions
    ),
    'currency', (SELECT min(currency) FROM active_subscriptions),
    'trial_to_paid_numerator', (
      SELECT count(*) FROM resolved_trials WHERE status = 'active'
    ),
    'trial_to_paid_denominator', (SELECT count(*) FROM resolved_trials),
    'trial_to_paid_percent', (
      SELECT CASE WHEN count(*) = 0 THEN NULL
        ELSE round(count(*) FILTER (WHERE status = 'active')::numeric / count(*)::numeric * 100, 1)
      END FROM resolved_trials
    )
  ) INTO v_result;

  RETURN v_result;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_investor_billing_snapshot(timestamptz,timestamptz) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_investor_billing_snapshot(timestamptz,timestamptz) TO authenticated;

CREATE OR REPLACE FUNCTION public.admin_investor_report_metrics(p_report_month date)
RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_month date := date_trunc('month', p_report_month)::date;
  v_current_month date := date_trunc('month', now() AT TIME ZONE 'Pacific/Auckland')::date;
  v_month_end date;
  v_previous_month date;
  v_previous_end date;
  v_trend_start date;
  v_cutoff timestamptz;
  v_previous_cutoff timestamptz;
  v_selected jsonb;
  v_previous jsonb;
  v_trend jsonb;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin'::app_role) THEN
    RAISE EXCEPTION 'not authorized';
  END IF;
  IF p_report_month IS NULL THEN
    RAISE EXCEPTION 'report month is required';
  END IF;
  IF v_month > v_current_month THEN
    RAISE EXCEPTION 'Future investor report months are not enabled.';
  END IF;

  v_month_end := CASE WHEN v_month = v_current_month
    THEN (now() AT TIME ZONE 'Pacific/Auckland')::date
    ELSE (v_month + interval '1 month - 1 day')::date END;
  v_previous_month := (v_month - interval '1 month')::date;
  v_previous_end := (v_month - interval '1 day')::date;
  v_trend_start := (v_month - interval '5 months')::date;

  -- Noon is used by the shared attendance layer for date-only programme
  -- sessions; end-of-day here is the month-end subscription snapshot.
  v_cutoff := CASE WHEN v_month = v_current_month THEN now()
    ELSE ((v_month + interval '1 month')::timestamp AT TIME ZONE 'Pacific/Auckland') - interval '1 microsecond' END;
  v_previous_cutoff := (v_month::timestamp AT TIME ZONE 'Pacific/Auckland') - interval '1 microsecond';

  v_selected := public.admin_reporting_dashboard(v_month, v_month_end, NULL, NULL, NULL, NULL);
  v_previous := public.admin_reporting_dashboard(v_previous_month, v_previous_end, NULL, NULL, NULL, NULL);
  v_trend := public.admin_reporting_dashboard(v_trend_start, v_month_end, NULL, NULL, NULL, NULL);

  -- The shared dashboard also contains Admin-only member drill-down rows.
  -- They are deliberately removed here: the investor builder needs aggregates
  -- only and must never receive member names or per-member histories.
  v_selected := v_selected - ARRAY['member_metrics', 'at_risk'];
  v_previous := v_previous - ARRAY['member_metrics', 'at_risk'];
  v_trend := v_trend - ARRAY['member_metrics', 'at_risk'];

  RETURN jsonb_build_object(
    'report_month', to_char(v_month, 'YYYY-MM'),
    'period_start', v_month,
    'period_end', v_month_end,
    'timezone', 'Pacific/Auckland',
    'is_incomplete_month', v_month = v_current_month,
    'metric_definition_version', 'admin-reporting-v1',
    'selected', v_selected,
    'previous', v_previous,
    'trend', v_trend,
    'billing', public.admin_investor_billing_snapshot(
      v_cutoff, v_month::timestamp AT TIME ZONE 'Pacific/Auckland'
    ),
    'previous_billing', public.admin_investor_billing_snapshot(
      v_previous_cutoff, v_previous_month::timestamp AT TIME ZONE 'Pacific/Auckland'
    ),
    'billing_trend', (
      SELECT COALESCE(jsonb_agg(jsonb_build_object(
        'month', to_char(month_start, 'YYYY-MM'),
        'snapshot', public.admin_investor_billing_snapshot(
          CASE WHEN month_start::date = v_current_month THEN now()
            ELSE ((month_start::date + interval '1 month')::timestamp AT TIME ZONE 'Pacific/Auckland') - interval '1 microsecond' END,
          month_start::date::timestamp AT TIME ZONE 'Pacific/Auckland'
        )
      ) ORDER BY month_start), '[]'::jsonb)
      FROM generate_series(v_trend_start, v_month, interval '1 month') AS months(month_start)
    ),
    'operations', jsonb_build_object(
      'active_locations', (
        SELECT count(DISTINCT location_id)
        FROM public.scheduled_sessions
        WHERE status <> 'cancelled'
          AND session_date BETWEEN v_month AND v_month_end
          AND location_id IS NOT NULL
      )
    ),
    'membership_snapshot', jsonb_build_object(
      'active_households', (
        SELECT count(DISTINCT d.household_id)
        FROM public.reporting_member_dimension d
        JOIN public.reporting_membership_intervals mi ON mi.profile_id = d.profile_id
        WHERE d.household_id IS NOT NULL
          AND mi.status IN ('active','trialing')
          AND mi.starts_at <= v_cutoff
          AND (mi.ends_at IS NULL OR mi.ends_at > v_cutoff)
      )
    ),
    'previous_membership_snapshot', jsonb_build_object(
      'active_households', (
        SELECT count(DISTINCT d.household_id)
        FROM public.reporting_member_dimension d
        JOIN public.reporting_membership_intervals mi ON mi.profile_id = d.profile_id
        WHERE d.household_id IS NOT NULL
          AND mi.status IN ('active','trialing')
          AND mi.starts_at <= v_previous_cutoff
          AND (mi.ends_at IS NULL OR mi.ends_at > v_previous_cutoff)
      )
    ),
    'previous_operations', jsonb_build_object(
      'active_locations', (
        SELECT count(DISTINCT location_id)
        FROM public.scheduled_sessions
        WHERE status <> 'cancelled'
          AND session_date BETWEEN v_previous_month AND v_previous_end
          AND location_id IS NOT NULL
      )
    ),
    'availability', jsonb_build_object(
      'referral', jsonb_build_object(
        'available', false,
        'reason', 'No reliable member-referral attribution field exists yet.'
      ),
      'cac', jsonb_build_object(
        'available', false,
        'reason', 'Acquisition spend and channel attribution are not yet captured together.'
      ),
      'contribution_margin', jsonb_build_object(
        'available', false,
        'reason', 'Direct location delivery costs are not yet captured.'
      ),
      'facilitator_mix', jsonb_build_object(
        'available', false,
        'reason', 'Sessions have facilitator attribution, but no canonical founder/non-founder flag exists.'
      )
    )
  );
END;
$$;

REVOKE ALL ON FUNCTION public.admin_investor_report_metrics(date) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_investor_report_metrics(date) TO authenticated;

-- ---------------------------------------------------------------------------
-- 4. Immutable Sent transition and explicit revisions
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.admin_mark_investor_report_sent(
  p_report_id uuid,
  p_metrics_snapshot jsonb,
  p_generated_html text,
  p_generated_text text
)
RETURNS public.investor_reports
LANGUAGE plpgsql VOLATILE SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_report public.investor_reports;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin'::app_role) THEN
    RAISE EXCEPTION 'not authorized';
  END IF;
  IF p_metrics_snapshot IS NULL OR p_metrics_snapshot = '{}'::jsonb
     OR NULLIF(btrim(p_generated_html), '') IS NULL
     OR NULLIF(btrim(p_generated_text), '') IS NULL THEN
    RAISE EXCEPTION 'A metric snapshot and final HTML/text are required.';
  END IF;

  UPDATE public.investor_reports
  SET status = 'sent', metrics_snapshot = p_metrics_snapshot,
      generated_html = p_generated_html, generated_text = p_generated_text,
      sent_at = now(), sent_by = auth.uid(), updated_by = auth.uid(),
      metrics_refreshed_at = COALESCE(metrics_refreshed_at, now())
  WHERE id = p_report_id AND status IN ('draft', 'ready')
  RETURNING * INTO v_report;

  IF v_report.id IS NULL THEN
    RAISE EXCEPTION 'Report was not found or is already immutable.';
  END IF;

  INSERT INTO public.investor_report_audit (report_id, event, actor_id, detail)
  VALUES (v_report.id, 'sent', auth.uid(), jsonb_build_object(
    'subject', v_report.subject,
    'metric_definition_version', v_report.metric_definition_version
  ));
  RETURN v_report;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_mark_investor_report_sent(uuid,jsonb,text,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_mark_investor_report_sent(uuid,jsonb,text,text) TO authenticated;

CREATE OR REPLACE FUNCTION public.admin_create_investor_report_revision(p_report_id uuid)
RETURNS public.investor_reports
LANGUAGE plpgsql VOLATILE SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_source public.investor_reports;
  v_report public.investor_reports;
  v_version integer;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin'::app_role) THEN
    RAISE EXCEPTION 'not authorized';
  END IF;

  SELECT * INTO v_source FROM public.investor_reports WHERE id = p_report_id;
  IF v_source.id IS NULL OR v_source.status NOT IN ('sent','archived') THEN
    RAISE EXCEPTION 'Only a Sent or Archived report can be revised.';
  END IF;
  SELECT COALESCE(max(version), 0) + 1 INTO v_version
  FROM public.investor_reports WHERE report_month = v_source.report_month;

  INSERT INTO public.investor_reports (
    report_month, version, revision_of, status, subject, preheader, headline,
    good, bad, ugly, learned_headline, learned_body, customer_quote,
    customer_quote_attribution, behaviour_change_numerator,
    behaviour_change_denominator, behaviour_change_period,
    behaviour_change_notes, family_signal_label, family_signal_numerator,
    family_signal_denominator, family_signal_notes, one_ask,
    selected_metric_ids, metrics_snapshot, metric_definition_version,
    metrics_refreshed_at, created_by, updated_by
  ) VALUES (
    v_source.report_month, v_version, v_source.id, 'draft', v_source.subject,
    v_source.preheader, v_source.headline, v_source.good, v_source.bad,
    v_source.ugly, v_source.learned_headline, v_source.learned_body,
    v_source.customer_quote, v_source.customer_quote_attribution,
    v_source.behaviour_change_numerator, v_source.behaviour_change_denominator,
    v_source.behaviour_change_period, v_source.behaviour_change_notes,
    v_source.family_signal_label, v_source.family_signal_numerator,
    v_source.family_signal_denominator, v_source.family_signal_notes,
    v_source.one_ask, v_source.selected_metric_ids, v_source.metrics_snapshot,
    v_source.metric_definition_version, v_source.metrics_refreshed_at,
    auth.uid(), auth.uid()
  ) RETURNING * INTO v_report;

  INSERT INTO public.investor_report_priorities
    (report_id, position, objective, target, status, outcome)
  SELECT v_report.id, position, objective, target, status, outcome
  FROM public.investor_report_priorities WHERE report_id = v_source.id;

  INSERT INTO public.investor_report_audit (report_id, event, actor_id, detail)
  VALUES (v_report.id, 'revision_created', auth.uid(),
          jsonb_build_object('revision_of', v_source.id, 'version', v_version));
  RETURN v_report;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_create_investor_report_revision(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_create_investor_report_revision(uuid) TO authenticated;
