-- Reflow the member-facing "Inner Wisdom" note into a single flowing line per
-- week. Removes the 'Dao:' / 'Inner reframe:' labels entirely, keeps the nature
-- image + the inner insight in one sentence, in Mindcast's own words. No deity,
-- no ACIM naming, and previously-quoted lines (e.g. 'This is water', a copyrighted
-- Tao translation) are paraphrased into original wording. Supersedes the label
-- text set by 20260711160000 / 20260724040000.

UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'What can be named is never the whole of you — the deepest signal lives beneath every label; you are not the image or the username, but the awareness behind it.', updated_at = now() WHERE week_number = 1;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Before the world ever named you, you were already whole; the self you have edited and defended over the years is not the real one.', updated_at = now() WHERE week_number = 2;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'There is a quiet space where action arises without forcing — between what happens and the story you tell about it, there is always a choice-point, and it is yours.', updated_at = now() WHERE week_number = 3;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Trust the felt current beneath the words; the body is a messenger, not the enemy — listen to it without judging.', updated_at = now() WHERE week_number = 4;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'A pool reflects clearly only once it stops being stirred; true seeing is looking at yourself without the filter of self-attack.', updated_at = now() WHERE week_number = 5;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'The bamboo does not envy the oak — each follows its own nature; comparison is a fear''s arithmetic, and your worth was never on the scale.', updated_at = now() WHERE week_number = 6;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Harshness hardens while softness endures — water wears down the hardest stone; the critic is only fear talking, and you can choose the kinder voice instead.', updated_at = now() WHERE week_number = 7;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Depth is reached by softening, not by forcing; every upset is a fear asking to be understood, not obeyed.', updated_at = now() WHERE week_number = 8;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'The valley receives every stream and is not broken by any of it; the wound is not who you are — healing is remembering the wholeness underneath it.', updated_at = now() WHERE week_number = 9;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Natural, unpolished and whole — like uncarved wood; the mask is an invented self, and the real one needs no performance.', updated_at = now() WHERE week_number = 10;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'The wise see through the eyes of everyone; whatever you choose to see in another, you strengthen in yourself.', updated_at = now() WHERE week_number = 11;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'A river carves a canyon drop by drop — small repeated action shapes everything; you become what you practise, so choose the pattern on purpose.', updated_at = now() WHERE week_number = 12;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Awareness is the water we forget we are swimming in — notice the medium itself; seeing clearly is the whole work, and everything else follows from it.', updated_at = now() WHERE week_number = 13;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'The way moves through willingness, not permission; you are the author of your own go-ahead — no outside verdict is needed.', updated_at = now() WHERE week_number = 14;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Return to the natural shape beneath the ones others imposed; the false self is only a costume, and you are free to take it off.', updated_at = now() WHERE week_number = 15;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'The soft and yielding outlast the rigid, and a clenched fist can receive nothing; forgiveness is dropping the story that keeps you in pain — a gift to yourself.', updated_at = now() WHERE week_number = 16;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Water does not war with the rock it flows past; it simply continues — guilt is not payment, so release yourself and let the lesson stay.', updated_at = now() WHERE week_number = 17;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'A wise gardener shapes by tending, not by scolding; change the voice you use inside and the whole inner weather changes.', updated_at = now() WHERE week_number = 18;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'A full cup cannot receive, so empty it to be useful — but choose what you pour; people-pleasing chases a verdict you already hold, so give from wholeness, not fear.', updated_at = now() WHERE week_number = 19;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'The way is inexhaustible — the more it gives, the more it has; what you extend, you strengthen, because love is not a limited supply.', updated_at = now() WHERE week_number = 20;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Honour the source, then walk your own path; keep the love that was real and gently release the fear that was taught.', updated_at = now() WHERE week_number = 21;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'What yields survives the storm that snaps the rigid; the armour you raise is what keeps the very closeness you long for at bay.', updated_at = now() WHERE week_number = 22;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'All things rise and return, and emptiness comes before new form; nothing real is lost — endings only reveal what was never only the form.', updated_at = now() WHERE week_number = 23;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Meet the current without gripping and fear softens when it is not fought; fear is a call for reassurance from your own inner voice, not a fact.', updated_at = now() WHERE week_number = 24;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'The map is not the territory — drop the smaller story to see the larger one; you are the author, not the character, and the pen is in your hand.', updated_at = now() WHERE week_number = 25;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Emptiness is what makes a cup useful — you have made room; laying down the false leaves only the real, and the real was never heavy.', updated_at = now() WHERE week_number = 26;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Know the constant within and you act from a settled centre; you are not built from labels — you choose what you extend and become.', updated_at = now() WHERE week_number = 27;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Follow your own nature and the path grows effortless; values are your inner voice choosing a direction, not rules imposed from outside.', updated_at = now() WHERE week_number = 28;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Great things are built from small ones, and a thousand-mile journey begins beneath your feet; each small choice quietly shapes the person you are becoming.', updated_at = now() WHERE week_number = 29;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Honour the body as the vessel that carries you — force nothing, restore in rhythm; care for the vessel so the inner life has a steady home.', updated_at = now() WHERE week_number = 30;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Keep company with what is natural and true; the relationships you tend teach you who you are, so choose the ones that call out your real self.', updated_at = now() WHERE week_number = 31;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Soft words and a steady centre govern the abrupt; the way you speak to yourself is the atmosphere you live in — be your own ally.', updated_at = now() WHERE week_number = 32;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'A wheel is useful because of both its ordered spokes and its empty hub; structure frees the mind from deciding, so it can simply be present.', updated_at = now() WHERE week_number = 33;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'In stillness, water clears itself — do less and arrive more; rest is trusting that you don''t have to force the day into shape.', updated_at = now() WHERE week_number = 34;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Creation flows when you stop forcing and let it move through you; expression is the self reaching outward, and joy — not judgement — is the measure.', updated_at = now() WHERE week_number = 35;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Each thing fulfils its own nature and the whole is served; your work is to extend your true self, and the world is completed by your particular light.', updated_at = now() WHERE week_number = 36;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Knowing when you have enough is the truest wealth; security is not a number — it is trust in your own inner sufficiency.', updated_at = now() WHERE week_number = 37;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'The valley gives to all and competes with none; belonging is built by extending yourself, not by earning a place.', updated_at = now() WHERE week_number = 38;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'The lasting way shows itself through steady character; becoming is really remembering — you are growing back into what was always true.', updated_at = now() WHERE week_number = 39;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'The wise hold onto nothing and so always have plenty to give; what you have received becomes complete only when you pass it on.', updated_at = now() WHERE week_number = 40;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'The wise teach mostly by how they live; to teach something is to strengthen it in yourself — you give and receive at once.', updated_at = now() WHERE week_number = 41;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'What is whole needs no polish to be enough; what you hide, you fear, and what you reveal to safe people, you begin to heal.', updated_at = now() WHERE week_number = 42;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'A deep-rooted tree bends in the gale and does not break; under pressure, return to your inner compass rather than the crowd''s fear.', updated_at = now() WHERE week_number = 43;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Yield and overcome — the gentle approach unties what force only pulls tighter; conflict is two people calling for the same thing, understanding, so answer that and not the attack.', updated_at = now() WHERE week_number = 44;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'The more you give, the more you have; to give is to keep, and what you extend you experience as your own.', updated_at = now() WHERE week_number = 45;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'One who knows they have enough is already rich; peace is not the next thing you acquire — it is noticing the fullness already here.', updated_at = now() WHERE week_number = 46;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Great things are accomplished by small steps taken steadily, without hurry; trust your own becoming — it is working even when unseen.', updated_at = now() WHERE week_number = 47;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Water benefits everything and asks nothing back; every encounter is a chance to add light, and you carry your state of mind with you wherever you go.', updated_at = now() WHERE week_number = 48;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'The wise act and leave no grasping behind, yet the good remains; what you extend outlives its form — a life given in love is the only legacy that is real.', updated_at = now() WHERE week_number = 49;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Contentment comes from receiving what is, fully; gratitude is choosing to see the good that fear overlooks.', updated_at = now() WHERE week_number = 50;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'The way has no end — you walk it by walking; the practice is the point, and you are always beginning again, which is exactly as it should be.', updated_at = now() WHERE week_number = 51;
UPDATE public.curriculum_weeks SET inner_wisdom_alignment = 'Return to the source and begin again, renewed; the end of the year is not a finish line but a remembering of who you have always been.', updated_at = now() WHERE week_number = 52;
