-- Modern 'signal metaphor' for each week, connected to that week's inner-wisdom
-- teaching + theme: the wisdom is the timeless principle; the metaphor makes it
-- concrete in today's world and shows how to live it ('Today: ...'). Stored on
-- curriculum_weeks alongside inner_wisdom_alignment, and mirrored onto
-- mindcast_live_sessions so the facilitator 'Signal Metaphor' slide uses it.

ALTER TABLE public.curriculum_weeks
  ADD COLUMN IF NOT EXISTS signal_metaphor text DEFAULT '';

UPDATE public.curriculum_weeks SET signal_metaphor = 'Your mind is a phone with 47 tabs open and notifications firing — the signal is the one tab you opened on purpose. Today: close the tabs (one breath, one thing) and hear the quiet channel underneath the noise.', updated_at = now() WHERE week_number = 1;
UPDATE public.curriculum_weeks SET signal_metaphor = 'The stories you tell about yourself run like an app in the background, quietly draining the battery. Today: catch one ''I''m the kind of person who…'' and ask — did I write this, or did it just install itself?', updated_at = now() WHERE week_number = 2;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Between the notification buzzing and your hand grabbing the phone there''s a half-second gap — that gap is a superpower. Today: find the buzz-to-grab gap in one habit and slot a single breath into it.', updated_at = now() WHERE week_number = 3;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Your body is the check-engine light your dashboard mind keeps ignoring — tight shoulders and a clenched jaw are data, not noise. Today: do a ten-second body scan before you fire back the stressful message.', updated_at = now() WHERE week_number = 4;
UPDATE public.curriculum_weeks SET signal_metaphor = 'The front camera shows every flaw; a good friend''s photo catches you laughing — self-awareness is choosing the friend''s lens. Today: describe yourself the way someone who loves you would.', updated_at = now() WHERE week_number = 5;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Scrolling compares your behind-the-scenes to everyone''s highlight reel — a treadmill where you sweat and never move. Today: name one ''race'' you''re quitting and mute the feed that runs it.', updated_at = now() WHERE week_number = 6;
UPDATE public.curriculum_weeks SET signal_metaphor = 'The inner critic is a group chat in your head that only ever roasts you — you can mute it and add a coach who''s honest but kind. Today: when the roast fires, ask ''would I say this to my best mate?''', updated_at = now() WHERE week_number = 7;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Anger is just the app icon; tap it and the real feeling opens underneath — fear, hurt, tiredness. Today: next time you''re ''grumpy'', open the icon and read what''s actually inside.', updated_at = now() WHERE week_number = 8;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Old hurts are a heavy backpack you''ve worn so long you forgot it''s on — naming them in a safe room is setting it down for a minute. Today: name one thing you''ve been carrying, just to feel the weight lift.', updated_at = now() WHERE week_number = 9;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Your profile is the filtered photo; the real you is the whole camera roll — and the right people want the camera roll. Today: show one true, unfiltered thing to someone safe.', updated_at = now() WHERE week_number = 10;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Everyone''s driving with a dashcam you can''t see — the person who cut you off might be racing to a hospital. Today: give one person the benefit of their unseen story.', updated_at = now() WHERE week_number = 11;
UPDATE public.curriculum_weeks SET signal_metaphor = 'A habit is an autoplay playlist — one trigger and the next track just starts. Today: spot the trigger track for one habit and swap the next song on purpose.', updated_at = now() WHERE week_number = 12;
UPDATE public.curriculum_weeks SET signal_metaphor = 'You''ve been handed a toolkit — a pause button, a feelings-iceberg, a mirror, a mute button for the critic. Today: pick the one tool you''ll actually keep in your pocket.', updated_at = now() WHERE week_number = 13;
UPDATE public.curriculum_weeks SET signal_metaphor = 'You keep refreshing an inbox for an approval email that''s never coming — because you''re the one who has to hit send. Today: give yourself the green light on one thing you''ve been waiting on.', updated_at = now() WHERE week_number = 14;
UPDATE public.curriculum_weeks SET signal_metaphor = 'You''ve been reading lines off a teleprompter someone else wrote — but it isn''t your story. Today: put down one ''should'' and say the line that''s actually yours.', updated_at = now() WHERE week_number = 15;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Resentment is gripping a hot coal to throw at someone — you''re the one getting burned. Today: name one grudge and picture opening your hand and setting the coal down.', updated_at = now() WHERE week_number = 16;
UPDATE public.curriculum_weeks SET signal_metaphor = 'You wouldn''t keep charging a friend for a debt they already paid — so stop billing yourself for the same mistake. Today: mark one thing ''paid — lesson kept'' and close the account.', updated_at = now() WHERE week_number = 17;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Swap the heckler in your head for a good coach — same honesty, opposite tone. Today: rewrite one harsh line the way a great coach would say it.', updated_at = now() WHERE week_number = 18;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Saying yes to everything is never closing any apps — your battery hits 1% by noon; a boundary is low-power mode on purpose. Today: turn one fear-''yes'' into an honest ''no''.', updated_at = now() WHERE week_number = 19;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Kindness isn''t a biscuit tin that empties — it''s a candle that lights other candles and loses nothing. Today: give something away as if it multiplies, because it does.', updated_at = now() WHERE week_number = 20;
UPDATE public.curriculum_weeks SET signal_metaphor = 'You inherited relationship ''settings'' the way a phone ships with defaults — some are great, some need updating. Today: spot one default about love you want to change.', updated_at = now() WHERE week_number = 21;
UPDATE public.curriculum_weeks SET signal_metaphor = 'The armour that got you through school now sets off the metal detector at the hug. Today: lower one piece of armour — sarcasm, busyness, control — with one safe person.', updated_at = now() WHERE week_number = 22;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Winter looks like the tree died, but it''s just clearing the branches for spring. Today: name what an ending has quietly made room for.', updated_at = now() WHERE week_number = 23;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Most alarms in your head are burnt toast, not a house fire — the smoke detector just can''t tell the difference. Today: label one fear ''burnt toast'' and open a window instead of running.', updated_at = now() WHERE week_number = 24;
UPDATE public.curriculum_weeks SET signal_metaphor = 'An old story is a saved route on your maps app that no longer goes where you live. Today: delete one outdated ''I always…'' and set a new destination.', updated_at = now() WHERE week_number = 25;
UPDATE public.curriculum_weeks SET signal_metaphor = 'You''ve cleared a pile of old apps clogging the phone — permission-seeking, resentment, armour. Today: notice how much lighter and faster you run without them.', updated_at = now() WHERE week_number = 26;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Instead of the labels stuck on you like airport baggage tags, you get to pack your own bag. Today: choose the three qualities you''re building yourself from.', updated_at = now() WHERE week_number = 27;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Values are your GPS ''home'' setting — every turn is easier once it''s locked in. Today: name your true-north value and check one recent decision against it.', updated_at = now() WHERE week_number = 28;
UPDATE public.curriculum_weeks SET signal_metaphor = 'You don''t get fit from one epic gym session — you get fit from showing up small and often; identity works the same. Today: pick the 1% habit you''ll repeat like brushing your teeth.', updated_at = now() WHERE week_number = 29;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Your body is the phone the whole day runs on, and sleep, movement, food and calm are the four charging cables. Today: plug in the one that''s most drained.', updated_at = now() WHERE week_number = 30;
UPDATE public.curriculum_weeks SET signal_metaphor = 'You become the average of your five most-opened contacts. Today: pick one relationship to open more, and one notification to turn down.', updated_at = now() WHERE week_number = 31;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Talk to yourself like you''d text a friend having a hard day — not like an anonymous troll in the comments. Today: keep one kind phrase in your pocket for the next hard moment.', updated_at = now() WHERE week_number = 32;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Routine isn''t a cage — it''s the trellis a plant climbs to reach the light. Today: add one small anchor (same wake time, one blocked hour) and let freedom grow on it.', updated_at = now() WHERE week_number = 33;
UPDATE public.curriculum_weeks SET signal_metaphor = 'You plug your phone in before it dies, not after — do the same for yourself. Today: schedule one real rest block before you''re down to 1%.', updated_at = now() WHERE week_number = 34;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Making something is like cooking for yourself — it doesn''t need a Michelin star to feed you. Today: make one small thing no one will grade.', updated_at = now() WHERE week_number = 35;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Purpose is where your skills and the world''s needs overlap — the sweet spot of the Venn diagram. Today: name one small place that overlap already exists.', updated_at = now() WHERE week_number = 36;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Your money ''scripts'' are inherited apps running in the background of every purchase. Today: sort one thing into need / want / could-share and notice which script ran.', updated_at = now() WHERE week_number = 37;
UPDATE public.curriculum_weeks SET signal_metaphor = 'A community is a beehive — it works because everyone brings something back. Today: name the one thing you''ll bring to a room you want to belong to.', updated_at = now() WHERE week_number = 38;
UPDATE public.curriculum_weeks SET signal_metaphor = 'The building site is now a home you can live in — identity, values, habits, people. Today: name who you''ve become, and step through the door into living it.', updated_at = now() WHERE week_number = 39;
UPDATE public.curriculum_weeks SET signal_metaphor = 'You don''t hoard the wifi password once you''re connected — you share it; inner work is the same. Today: give one thing you''ve healed enough to offer someone else.', updated_at = now() WHERE week_number = 40;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Explaining something to a ten-year-old is how you find out you actually understand it. Today: put one lesson into one plain sentence and pass it on.', updated_at = now() WHERE week_number = 41;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Turning your camera on in the meeting is scary for two seconds and connecting for the rest. Today: show up ''camera-on'' in one place you usually hide.', updated_at = now() WHERE week_number = 42;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Your values are only real in the storm, not the sunshine — like a compass that has to work when the sky goes dark. Today: name one value you''ll hold even when it costs you.', updated_at = now() WHERE week_number = 43;
UPDATE public.curriculum_weeks SET signal_metaphor = '''You always…'' starts a fight; ''I feel… I need…'' starts a conversation. Today: rewrite one hard message in the second language.', updated_at = now() WHERE week_number = 44;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Some gifts — encouragement, time, attention — cost nothing and still glow in your own hands after you give them. Today: give one non-money gift by Sunday.', updated_at = now() WHERE week_number = 45;
UPDATE public.curriculum_weeks SET signal_metaphor = 'The ''add to cart'' feeling is a treadmill — one more thing never becomes enough. Today: name three things you already have that are genuinely enough.', updated_at = now() WHERE week_number = 46;
UPDATE public.curriculum_weeks SET signal_metaphor = 'A seed spends weeks looking like nothing while it grows roots — don''t dig it up to check. Today: recommit to one slow, unglamorous thing that''s still growing underground.', updated_at = now() WHERE week_number = 47;
UPDATE public.curriculum_weeks SET signal_metaphor = 'You leave a ''tip'' in every interaction — a little brighter or a little dimmer. Today: leave one person brighter, on purpose.', updated_at = now() WHERE week_number = 48;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Drop a stone in a pond and the ripples reach edges you''ll never see. Today: name one mark you want rippling out from how you live.', updated_at = now() WHERE week_number = 49;
UPDATE public.curriculum_weeks SET signal_metaphor = 'Gratitude is a camera — the more you practise pointing it, the more good it finds in frame. Today: capture three specific good moments in words, not generic ones.', updated_at = now() WHERE week_number = 50;
UPDATE public.curriculum_weeks SET signal_metaphor = 'There''s no ''finish line'' notification for growth — the walk is the point. Today: name the one practice you''ll keep for life, arrival or not.', updated_at = now() WHERE week_number = 51;
UPDATE public.curriculum_weeks SET signal_metaphor = 'You''re not closing a book, you''re turning to a blank page with a full backpack and a compass. Today: write the first line of next year''s chapter.', updated_at = now() WHERE week_number = 52;

-- Mirror onto the live-session deck for every track so the metaphor slide matches.
UPDATE public.mindcast_live_sessions ms
SET signal_metaphor = cw.signal_metaphor
FROM public.curriculum_weeks cw
WHERE ms.week_number = cw.week_number AND COALESCE(cw.signal_metaphor,'') <> '';

